### ISSUE TITLE
How to use phpsocket.io as a client to recv message from other server.

### ISSUE THREAD

**Issue by brucetam** [walkor/phpsocket.io#103]
你好，我们在使用这个库的时候有一个问题，phpsocket.io能否作为客户端接收其他服务器的推送？
我是参考http://doc3.workerman.net/faqas-wss-client.html 写的，能不能用AsyncTcpConnection库，同时拥有emit的方法发送信息给服务器？因为服务器端会监听这相应的事件，不想用node.js作为后端的客户端所以服务器端跟客户端都用PHP，代码请参考如下，相应的问题也有标注，非常感谢你的回复！
$worker = new Worker();
$worker->onWorkerStart = function($worker)
{
    $ws_connection = new AsyncTcpConnection("http://127.0.0.1:1935");
    $ws_connection->onConnect = function($ws_connection){
        $data =array('login'=>array('access_token'=>'51d2312026b9a3baad0f1d0b62e2297b9ce23af19171ac450df99c0e6e','room_id'=>120));
        $ws_connection->send(json_encode($data));
        $ws_connection->emit('init_msg',json_encode($data)); // 可否这么写，因为服务端是监听着init_msg事件
    };
    $ws_connection->on('server_resp',function($data){ //可否这么写，像socket.io一样监听服务端的事件
        echo $data;
    })
    $ws_connection->onMessage = function($ws_connection, $data){
        echo "recv: $data\n";
        var_dump($ws_connection);
    };
    $ws_connection->onError = function($ws_connection, $code, $msg){
        echo "error: $msg\n";
    };
    $ws_connection->onClose = function($ws_connection){
        echo "connection closed\n";
    };
    $ws_connection->connect();
};

**Comment by walkor** [comment]
Please use english, that can help all people to understand each other. Thanks. : -)
Or you can send your issue to http://wenda.workerman.net/ which is for chinese community.

**Comment by brucetam** [comment]
ok, how can I use emit function if I am using AsyncTcpConnection object ?
Because the peer server is using node.js+socketio.js and I want to send message to it.

**Comment by brucetam** [comment]
To simplify, my question is how to send websocket protocol data if I am using AsyncTcpConnection object ?

**Comment by walkor** [comment]
Here is an example for how to using AsyncTcpConnection  as a websocket client.
```php
require_once __DIR__ . '/vendor/autoload.php';
use Workerman\Worker;
use Workerman\Connection\AsyncTcpConnection;

$worker = new Worker();
$worker->onWorkerStart = function()
{
    // Websocket protocol for client.
    $ws_connection = new AsyncTcpConnection("ws://echo.websocket.org:80");
    $ws_connection->onConnect = function($connection){
        $connection->send('hello');
    };
    $ws_connection->onMessage = function($connection, $data){
        echo "recv: $data\n";
    };
    $ws_connection->onError = function($connection, $code, $msg){
        echo "error: $msg\n";
    };
    $ws_connection->onClose = function($connection){
        echo "connection closed\n";
    };
    $ws_connection->connect();
};
Worker::runAll();
```

**Comment by brucetam** [comment]
but how can I use emit function like in socket server ? Because the peer server only accept "chat_msg" event, for example code below:
        $connection->emit('chat_msg',$json_data);

**Comment by walkor** [comment]
AsyncTcpConnection is not  a socket.io client and it does not have emit method.
You have to implement the emit method based on AsyncTcpConnection it you want that.
To do this, you need to understand the communication mechanism of socket.io which you can find it by checking network of chrome browser.

**Comment by zuohuadong** [comment]
socket.io can be used as a client or server.
so, phpsocket.io ......

**Comment by FlameStorm** [comment]
Hello from 2020!
So, what about well-done and ready-to-use PHP websocket client based on phpsocket.io?
