### ISSUE TITLE
How to reconnect a user in their previous state?

### ISSUE THREAD

**Issue by DavidWilliamBalbino** [walkor/phpsocket.io#104]
How to reconnect a user in their previous state?

Example:

In my database, there is a user with the ID number 10, but his internet has dropped, and when he reconnects, how do I get him back with the same socketid he had before the internet crashed? Or some good practice to do this.

**Comment by LegitSoulja** [comment]
Ok, so. Let's learn how to code.

The connecting client, get his ip address, or something you can compare with. Index through the connected clients. Place him @ that index if something matches back.

No hard. But, why would you want the ID's static?
