### ISSUE TITLE
socket.io Failed to load resources

### ISSUE THREAD

**Issue by DeeCann** [walkor/phpsocket.io#107]
Hi,
I've got an issue with Failed to load resources on http://mydomain.com:2206/socket.io/ . It seems like server doesn't work but Server.php status is ok. I was thinking that something is wrong with my configuration but then I checked demo on http://www.workerman.net/demos/phpsocketio-chat/ and the same problem is there.
![zrzut ekranu 2017-08-07 o 13 24 21](https://user-images.githubusercontent.com/9107948/29058515-fb9799b2-7c10-11e7-82d1-df907451ed0f.png)

Any suggestions ?

**Comment by walkor** [comment]
I tried this link http://www.workerman.net/demos/phpsocketio-chat/ and it worker fine for me.
Can you test it in chrome?

**Comment by DeeCann** [comment]
I'm testing this on MacBook on Chrome ver. 60.0.3112.90

**Comment by walkor** [comment]
Please run phpsocket.io as debug mode with command ```php start.php start```(without ```-d```) and see if any error output in your terminal.

**Comment by DeeCann** [comment]
Nothing there. You are saying that http://www.workerman.net/demos/phpsocketio-chat/ is working fine for you ? So what can be wrong ?

**Comment by DeeCann** [comment]
Here is status:
<img width="777" alt="zrzut ekranu 2017-08-08 o 12 48 12" src="https://user-images.githubusercontent.com/9107948/29068616-d682e59c-7c37-11e7-8e72-3e0eb03caec2.png">

**Comment by walkor** [comment]
From the status we can see your phpsocket.io process terminated 23 times . 
Do you called ```exit()``` or ```die``` in phpsocket.io?

**Comment by DeeCann** [comment]
Both of them, nothing changed, what's the difference ? But for me strange thing is that phpsocket.io is not working at all, not only on my site but on demos.

**Comment by walkor** [comment]
It's strange that phpsocket.io works well with me, and I'm not sure what's wrong with it.
