### ISSUE TITLE
How to use phpsocket.io to send some specified users at the same time? 

### ISSUE THREAD

**Issue by JohnLiuQiang** [walkor/phpsocket.io#108]
I am writing an programme as Taxi drops. I need send an order Information to some specified drivers at the same time. But I do not know how to use phpsocket.io to finish it.

**Comment by walkor** [comment]
Please use [GatewayWorker](https://github.com/walkor/GatewayWorker) to do that.
Here is the [document](http://doc2.workerman.net/326102).

**Clients libraries** 
https://github.com/daltoniam/Starscream
https://github.com/facebook/SocketRocket
https://github.com/koush/AndroidAsync

**Comment by JohnLiuQiang** [comment]
Thinks a lot!
