### ISSUE TITLE
redis for pub/sub 

### ISSUE THREAD

**Issue by irinakrisa** [walkor/phpsocket.io#110]
`<?php`
`require_once __DIR__ . '/vendor/autoload.php';`
`use Clue\React\Redis\Factory;`
`use Clue\React\Redis\Client;`
`use Workerman\Worker;`
`use PHPSocketIO\SocketIO;`

`// listen port 2021 for socket.io client`
`$io = new SocketIO(2021);`
`$io->on('workerStart', function() use ($io){`
`    $loop    = Worker::getEventLoop();`
`    $io->factory = new Factory($loop);`
`    $io->factory->createClient('127.0.0.1:6379')->then(function (Client $client) use ($io) {`
`        // ==== Assign to $io->redis ==== `
`        $io->redis = $client;`
`        $io->redis->subscribe('some_event')->then(function () {/*...*/});`
`    });`
`});`

`$io->on('connection', function($socket)use($io){`
`  $socket->on('chat message', function($msg)use($io){`
`      $io->redis->subscribe($msg)->then(function () {`
`            echo 'Now subscribed to channel ' . PHP_EOL;`
`       });`
`      $io->emit('chat message', $msg);`
`  });`

`Worker::runAll();`

> Fatal error: Uncaught Error: Call to a member function subscribe() on null

**Comment by walkor** [comment]
```php
$io->factory->createClient('127.0.0.1:6379')->then(function (Client $client) use ($io) {
        // ==== Assign to $io->redis ==== 
        $io->redis = $client;
        $io->redis->subscribe('some_event')->then(function () {/*...*/});
});
```
```then(function(Client $client)use($io){...})``` may not called(some error occurred) or ```chat message```  called before that called.

**Comment by irinakrisa** [comment]
I used this - [issues](https://github.com/walkor/phpsocket.io/issues/62), but gives an error. Is it possible that the redis is not connected correctly?

**Comment by walkor** [comment]
yes, redis may not connected.

**Comment by irinakrisa** [comment]
Thanks, the problem was in php7. But now I have a new mistake. How to make, what on a redis1 time subscribed?
