### ISSUE TITLE
How to add route in Web server of workerman

### ISSUE THREAD

**Issue by willowTank** [walkor/phpsocket.io#113]
I want to add route in web server. How can i do it?
Best Regards

**Comment by walkor** [comment]
What route?.
Can you provide examples?

**Comment by willowTank** [comment]
This is python sample
`
@app.route('/')
def index():
    resp = make_response(render_template('index.html'))
    try:
        id = request.values['userid']
        if api.user_verify(id) ==True:
            resp.set_cookie("id", id)
    except KeyError as e:
        headers = ""
    return resp

@app.route('/user-info',  methods=['POST'])
def user_info():
    status = 200
    res = ""
    try:
        id = request.cookies['id']
        res = '[10000,3,1000,1000,"'+id+'",1,1000,1000]'
        status = 200
    except KeyError as e:
        status = 401
    return Response(res, mimetype='application/json'), status

@app.route('/maintenance', methods=['POST'])
def maintenance():
    res = {"state": 0, "content":"", "isBlockChat":0}
    return Response('{"state": 0, "content":"", "isBlockChat":0}', mimetype='application/json')

@app.route('/ott', methods=['POST'])
def ott():
    status = 200
    res = ""
    try:
        id = request.cookies['id']
        res = api.ott(id)
        status = 200
    except KeyError as e:
        status = 401
    return Response(res, mimetype='application/json'),status`

How can I implement it on php walkor web server

**Comment by walkor** [comment]
Here is an example.
https://github.com/xtgxiso/WebWorker

**Comment by willowTank** [comment]
Thanks for your fast reply.

**Comment by willowTank** [comment]
now I am using php5.4.45. I cann't fetch it from github. Please let me know other method.
Best Regards

**Comment by walkor** [comment]
The best way is upgrade your php.

**Comment by willowTank** [comment]
Hello I would use onMessage function.
```

$web = new WebServer('http://0.0.0.0:8881');
$web->onMessage = onMessage;

$web->addRoot('localhost', __DIR__ . '/static');
if (!defined('GLOBAL_START')) {
    Worker::runAll();
}

function onMessage($connection) {
    print_r($param);
}
```

But it is not working. Please help me. Best Regards

**Comment by walkor** [comment]
WebServer not support onMessage callback.
You can use Worker like this.
```
$web = new Worker('http://0.0.0.0:8881');
$web->onMessage = onMessage;
...
```
