### ISSUE TITLE
MYSQL

### ISSUE THREAD

**Issue by RayHughes** [walkor/phpsocket.io#115]
Do you have an example that uses MYSQL?

**Comment by softwaredeveloperca** [comment]
Take a look at something roughly I did.  

Db.php is a single file DB class.
Game.php is a class that uses DB class.
start_io.php is the class that gets the call and creates a new game class.

https://github.com/softwaredeveloperca/MovieGame-Backend-phpsocket.io/blob/master/examples/chat/start_io.php

https://github.com/softwaredeveloperca/MovieGame-Backend-phpsocket.io/blob/master/src/Models/Game.php

https://github.com/softwaredeveloperca/MovieGame-Backend-phpsocket.io/blob/master/src/Models/Db.php
