### ISSUE TITLE
"Trying to get property of non-object"

### ISSUE THREAD

**Issue by thrieu** [walkor/phpsocket.io#12]
I run a modified web-msg-sender instance on my server, today it threw the following error and stop working:

> Trying to get property of non-object in ***/vendor/workerman/phpsocket.io/src/Engine/Socket.php:40

I think it is due to phpsocket.io but not my modification.I cannot reproduce the bug again, it is accidental.

**Comment by walkor** [comment]
Finding the problem seems a bit difficult, I will try to fix it.
Thanks for your issue.
