### ISSUE TITLE
https net::ERR_TIMED_OUT

### ISSUE THREAD

**Issue by duchao1990** [walkor/phpsocket.io#120]
webmsgserver:

$context = array(
    'ssl' => array(
        'local_cert'  => __DIR__.'/www.cp168.online.pem', 
        'local_pk'    => __DIR__.'/www.cp168.online.key',
        'verify_peer' => false,
    )
);
// PHPSocketIO服务
$sender_io = new SocketIO(8004,$context);

js scoket

 var socket = io('https://www.cp168.online:8004');

aliyunserver 安全组

![image](https://user-images.githubusercontent.com/9289694/31595365-cd8c5d76-b26d-11e7-914c-2d9ea6e9ba65.png)

服务器:
![image](https://user-images.githubusercontent.com/9289694/31595371-dd91e57e-b26d-11e7-947f-abee37ff35e7.png)

链接超时:socket.io.js:2919 GET https://www.cp168.online:8004/socket.io/?EIO=3&transport=polling&t=1508128506786-7 net::ERR_TIMED_OUT

特别着急,前边的issues 我也看了,但是就是连不上,特别着急谢谢

**Comment by duchao1990** [comment]
__DIR__

**Comment by walkor** [comment]
It is not phpsocket.io 's issue.
Please create a issue to aliyun.
