### ISSUE TITLE
net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by youngwoonkim** [walkor/phpsocket.io#121]
http://localhost:2020/socket.io/?EIO=3&transport=polling&t=LzHGZVx 

web console msg 
- connect_error :  Error: xhr poll error

**Comment by walkor** [comment]
Do you start your phpsocket.io ?

**Comment by youngwoonkim** [comment]
yes.
Here is my example code:
require __DIR__ . '/../vendor/workerman/workerman/Worker.php';
require __DIR__ . '/../vendor/workerman/phpsocket.io/src/SocketIO.php';

use PHPSocketIO\SocketIO;
use Workerman\Worker;

$io = new SocketIO(2020);

$io->on('connection', function($socket)use($io){

    $socket->on('getMainList', function ($data)use($socket){
        // we tell the client to execute 'new message'
        $io->socket->emit('test1', array(
            'status'=> 200,
            'message'=> 'ok test1'
        ));
    });

    $socket->on('checkChangeResult', function ($data)use($io){
        // we tell the client to execute 'new message'
        $socket->broadcast->emit('test2', array(
            'status'=> 200,
            'message'=> 'ok test2'
        ));
    });
});

Worker::runAll();

Do you need to add more here or are you missing?

**Comment by walkor** [comment]
![image](https://user-images.githubusercontent.com/6073368/31981683-7beec194-b91a-11e7-8529-2bd8162f5fc7.png)
Do you start your phpsocket.io like this?

**Comment by youngwoonkim** [comment]
It is the same. The problem is solved. The reason is the window environment, but I have a win version in other issues.
