### ISSUE TITLE
Worker count in socketIO

### ISSUE THREAD

**Issue by denfm** [walkor/phpsocket.io#123]
Hello,

Could you please tell why is it impossible to specify the number of workers in PHPSocketIO like it was in Workerman\Worker?

Thx!

**Comment by walkor** [comment]
Socket.io's handshake has multiple communication, the browser may establish multiple connections, which may connect in different processes, resulting in the previous communication information missing, resulting in handshake failure.

**Comment by denfm** [comment]
Ok. 
Then could you please tell how to correctly implement the code of handler of requests from the socket, so that client1 doesn't wait while the request from client10 is processed?
For example, when using such code:
`$socket->on('test', function() use($socket) {
                sleep(10);
                $socket->emit('messages', ['OK!']);
            });`

**Comment by walkor** [comment]
These links may help.
https://github.com/walkor/Workerman/issues/165
https://github.com/walkor/Workerman/issues/203
