### ISSUE TITLE
tcp connection keep growing and won't release

### ISSUE THREAD

**Issue by brucetam** [walkor/phpsocket.io#124]
Hi walkor,

I am using phpsocket.io as websocket backend service and found one issue when I was developing.
Every time I try to connect to socket server from client(mobile app/browser), it will establish 3 tcp connections, when I close the socket from client side, 1 tcp connections had been closed, but 2 left tcp connection are still established and won't close anymore, which caused the server tcp connection keep growing and reach the limitation then drop incoming connections, did you see this case and how can i fix this ?
Many thanks.

**Comment by walkor** [comment]
I didn't reproduce this problem.
Have anyone ever met this problem?

**Comment by twizdev** [comment]
It seems to happen when using Cloudflare CDN.

**Comment by brucetam** [comment]
@twizdev exactly right when i was using Cloudflare CDN.
