### ISSUE TITLE
Emit to room in a worker timer

### ISSUE THREAD

**Issue by dnagikh** [walkor/phpsocket.io#125]
Hello!

I have a hundred of rooms like CLIENT1-ROOM1, CLIENT1-ROOM2, CLIENT2-ROOM1, CLIENT3-ROOM1, CLIENT3-ROOM2, CLIENT3-ROOM3, etc.

My worker:
```
use Workerman\Worker;
use PHPSocketIO\SocketIO;
use Workerman\Lib\Timer;

$io = new SocketIO(2346);

$time_interval = 1;
$timer_id = Timer::add($time_interval,
    function() use ($io)
    {
        $io->to('CLIENT1-ROOM1')->emit('message', 'Test message');
    }
);

$io->on('connection', function($socket) use ($io) {
    $socket->join('CLIENT1-ROOM1');
    echo "New connection #" . $socket->id . "\n";
});

Worker::runAll();
```

Timer will send messages to rooms every second. Each room has its own messages.
So after I connect to my worker from front-end:
```
    var socket = io('http://'+document.domain+':2346');

    socket.on('message', function (data) {
        console.log(data);
    });
```

I do not get any messages...

Although If I put my timer in io connection callback, it works, but each connection runs new timer and users get several messages every second

Is it cache in Timer? Or how can I solve this by one timer?

P.S. Timer will have massive function with db connection and difficult processing. I try to optimize server recourses by one timer.

Thanks!

**Comment by walkor** [comment]
Try these codes.
```php
use Workerman\Worker;
use PHPSocketIO\SocketIO;
use Workerman\Lib\Timer;

$io = new SocketIO(2346);

$io->on('workerStart', function()use($io){
    $time_interval = 1;
    $timer_id = Timer::add($time_interval,
        function() use ($io)
        {
            $io->to('CLIENT1-ROOM1')->emit('message', 'Test message');
        }
    );
});

$io->on('connection', function($socket) use ($io) {
    $socket->join('CLIENT1-ROOM1');
    echo "New connection #" . $socket->id . "\n";
});

Worker::runAll();
```

**Comment by dnagikh** [comment]
Yeah, it works! Thank you very much!
