### ISSUE TITLE
如何解决平滑启动php server.php reload的问题

### ISSUE THREAD

**Issue by zhengweiman** [walkor/phpsocket.io#126]
php server.php start stop  restart  status
这些操作都是没问题的，但是执行 php server.php reload 就没有效果了。
以下是返回结果：
 php server.php reload
Workerman[server.php] reload
Workerman[server.php] reload
请问有什么解决方案吗？

**Comment by walkor** [comment]
中文提问到这里提问吧
http://wenda.workerman.net/

这里是英语社区，不方便用中文。感谢支持。
