### ISSUE TITLE
Emit messages from PHP client to Node.js server

### ISSUE THREAD

**Issue by DenisAlliswell** [walkor/phpsocket.io#129]
Hello, @walkor.

First of all, thank you for the great work with this repo!

My question.
I have PHP project with Node.js+Socket.io realtime server (it works as proxy on nginx). In some cases I need to emit/broadcast messages from PHP to Node.js server (or at least to socket.io-client).

How can I do this?

**Comment by walkor** [comment]
Sorry. I'm not familiar with socket.io of nodejs, so I can't give any advice.

**Comment by DenisAlliswell** [comment]
Ok, then how I can emit message from PHP client to phpsocket.io server?

**Comment by walkor** [comment]
See https://github.com/walkor/phpsocket.io/issues/23

**Comment by DenisAlliswell** [comment]
Thank you!
