### ISSUE TITLE
problem with ssl

### ISSUE THREAD

**Issue by soha1410** [walkor/phpsocket.io#131]
Hi , I have a problem with ssl , 
`$context = array(
    'ssl' => array(
        'local_cert' => '/etc/httpd/ssl/apache.pem',
        'local_pk'   => '/etc/httpd/ssl/apache.key',
    )
);
$io    = new SocketIO(2024,$context);`
running of 
`php socket.php start`
```
stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:  
  error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:  
  error:14094416:SSL routines:SSL3_READ_BYTES:sslv3 alert certificate unknown 
stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:  
  error:1407609C:SSL routines:SSL23_GET_CLIENT_HELLO:http request 
```

**Comment by walkor** [comment]
It looks like certificate problem. It may be an illegal certificate.
It may also be that the client does not access through HTTPS, but is accessed by http.
