### ISSUE TITLE
Emit to specific SID

### ISSUE THREAD

**Issue by khvalov** [walkor/phpsocket.io#133]
Hi, is any functionality implemented  to emit message to exact sid? like:
`  $socket->to($socket->id)->emit('pingback',['hello'=>'world']);`
(Same functionality for socket.io described https://stackoverflow.com/questions/24041220/sending-message-to-a-specific-id-in-socket-io-1-0)

**Comment by walkor** [comment]
Try the codes.
```php
$io->to($socket->id)->emit('pingback',['hello'=>'world']);
```

**Comment by khvalov** [comment]
Thumbs up! Exactly what i'm looking for.

Thanks!

**Comment by lokomass** [comment]
Hi, this not work for me,
Can you help me ?

`$io -> on('connection', function($socket) {
		$socket -> on('update-friend', function($data) use($socket) {
			global $array;
			$socket -> to($array[$data]) -> emit('update-friends');
		});
		$socket -> on('login', function($data) use($socket) {
			global $array;
			$id = $socket -> id;
			$array[$data] = $id;
		});
	});`

**Comment by walkor** [comment]
Not `$socket->to($array[$data])` but `$io->to($array[$data])`.
This is the right codes.
```php
$io -> on('connection', function($socket) use ($io) {
        $socket -> on('update-friend', function($data) use($io) {
                global $array;
                $io -> to($array[$data]) -> emit('update-friends');
        });
        $socket -> on('login', function($data) use($socket) {
                global $array;
                $id = $socket -> id;
                $array[$data] = $id;
        });
});
```

**Comment by lokomass** [comment]
Thanks for reply, but same result. This is not work.
The 'update-friend' event is fired.
$array[$data] is the id of socket to send request.

**Comment by walkor** [comment]
![image](https://user-images.githubusercontent.com/6073368/94115951-fea75380-fe7c-11ea-8a45-20ce8ceb5e7f.png)

**Comment by lokomass** [comment]
Amazing, this work perfect ! Thanks !
