### ISSUE TITLE
How to run server using Codeigniter?

### ISSUE THREAD

**Issue by AntistasII** [walkor/phpsocket.io#134]
Hello!
Thanks for your work!
So, I need to do this to run server
**php server.php start**
But i am using Codeigniter framework, and I am doing this to run php code
**php index.php cotroller_name method_name**
And terminal responds 
**Usage: yourfile.php {start|status..... }** 
My questions is how to run server using codeigniter if I instead **{start|status....}** write **controller method**?

**Comment by atukilham** [comment]
Put your file (ex: server.php) in your web root folder

**Comment by AntistasII** [comment]
@atukilham But If i want to create server like method in controller? Is it possible? 
My idea is make server like part of controller for using methods, libraries etc.

**Comment by DavidWilliamBalbino** [comment]
Maybe this will help you.
https://github.com/ericterpstra/ci_sock

**Comment by PhamMinhKha** [comment]
change file /vender/wokerman/wokerman/Worker.php
go to line 872
`$usage = "Usage: php yourfile <command> [mode]\nCommands: \nstart\t\tStart worker in DEBUG mode.\n\t\tUse mode -d to start in DAEMON mode.\nstop\t\tStop worker.\n\t\tUse mode -g to stop gracefully.\nrestart\t\tRestart workers.\n\t\tUse mode -d to start in DAEMON mode.\n\t\tUse mode -g to stop gracefully.\nreload\t\tReload codes.\n\t\tUse mode -g to reload gracefully.\nstatus\t\tGet worker status.\n\t\tUse mode -d to show live status.\nconnections\tGet worker connections.\n";
        if (!isset($argv[3]) || !\in_array($argv[3], $available_commands)) {
            if (isset($argv[3])) {
                static::safeEcho('Unknown command: ' . $argv[3] . "\n");
            }
            exit($usage);
        }

        // Get command.
        $command  = \trim($argv[3]);
        $command2 = isset($argv[4]) ? $argv[4] : '';`
run `php /var/www/html/index.php C_socketio index start
`
