### ISSUE TITLE
There is a recommended way to perform HTTP POST requests within (PHP)SocketIO loop?

### ISSUE THREAD

**Issue by LuckyCyborg** [walkor/phpsocket.io#139]
Hi, @walkor 

As probably you already know, I written for Nova Framework a Push Server named **Quasar**, in the top of PHPSocketIO: https://github.com/nova-framework/quasar and its client script is here: https://github.com/nova-framework/framework/blob/4.0/assets/js/quasar.js

Both **Workerman** and **PHPSocketIO** do a fine job behind tables, and I wish to say sincere congratulations for those nice designs.

But I have some questions.

A client site push its messages to Quasar instance via POST requests sent to the Qusar's HTTP server and pass them to the SocketIO server, which do the dispatch to users.

The Quasar's SocketIO server use three types of channels (rooms), as **public**, **private** and **presence**. And for the last two types, it requires a particular authentication with the help of the client site, a bit similar as logic with the well known **Pusher**.

Basically, we talk about a way to subscribe and leave (voluntary or on disconnection) to those private and presence channels, using certain tokens generated by the client site and recognized by the push server.

Now, imagine that the user opens a page which subscribe to a presence channel, and the site should know precisely the time period of user's visiting this page.

Sure thing, the site can known when to start the count, because the page is served by it, or even within a complete page caching, the Quasar's JS client sends to site a POST request for the subscription token. 

BUT, how the MVC site, running on top of Apache or NGINX, can know when the user leave the page, for example closing the browser? 

Of course, the Push Server knows precisely when happens this event, as the client socket disconnects. 

So, the logic idea of that instructing the SocketIO loop to send an HTTP POST request to a certain API end-point from site,  this particular site could be informed about disconnection event.

And here we arrive to my question: _there is a recommended way to perform HTTP POST requests within SocketIO loop, as this feature to have a minimal impact over overall loop's performance, considering that it is event driven?

The second question is if there is a way to instruct the PHPSocketIO to use particular **Socket** and **Nsp** classes, which extends the base/original classes. I felt the need to extend them, because not everything can be written fluently in the `on()` commands, you know... :smirk:

**Comment by walkor** [comment]
Good job for Nova Framework and Quasar.
I wrote a pusher-server with workerman before, and there is a function that you may be useful to you.
```php
use Workerman\Connection\AsyncTcpConnection; 
    protected function sendHttpRequest($address, $app_key, $secret, $body)
    {
        $address_info = parse_url($address);
        if (!$address_info) {
            echo new \Exception('bad remote_address');
            return false;
        }

        if (!isset($address_info['port'])) {
            $address_info['port'] = 80;
        }
        if (!isset($address_info['path'])) {
            $address_info['path'] = '/';
        }
        if (!isset($address_info['query'])) {
            $address_info['query'] = '';
        } else {
            $address_info['query'] = '?' . $address_info['query'];
        }
        $remote_address = "{$address_info['host']}:{$address_info['port']}";
        $remote_host    = $address_info['host'];
        $remote_URI     = "{$address_info['path']}{$address_info['query']}";
        $scheme         = isset($address_info['scheme']) && $address_info['scheme'] === 'https' ? 'ssl' : 'tcp';
        $signature      = hash_hmac('sha256', $body, $secret, false);

        $header = "POST $remote_URI HTTP/1.0\r\n";
        $header .= "Host: $remote_host\r\n";
        $header .= "Connection: close\r\n";
        $header .= "X-Pusher-Key: $app_key\r\n";
        $header .= "X-Pusher-Signature: $signature\r\n";
        $header .= "Content-Type: application/json\r\n";
        $header .= "Content-Length: " . strlen($body);
        $http_buffer = $header."\r\n\r\n".$body;

        $client = new AsyncTcpConnection($scheme.'://'.$remote_address);
        $client->onConnect = function ($client) use ($http_buffer) {
            $client->send($http_buffer);
        };
        $client->onMessage = function($client, $buffer) {
            echo $buffer."\n\n";
        };
        // close the connection 10 seconds after. 
        Timer::add(10, array($client, 'close'), null, false);
        $client->connect();
    }
```

For the second question I don't have a very good idea at the moment.

**Comment by LuckyCyborg** [comment]
Thanks for the snippet, it is exactly what I want. 

And talking about the second question, there is a way to optionally customize those classes: https://github.com/walkor/phpsocket.io/pull/140

I hope you will agree with this pull request, then you'll be kind to release a new version, to permit to keep my trees in sync with your repositories.
