### ISSUE TITLE
use phpsocket.io as client 

### ISSUE THREAD

**Issue by 961900832** [walkor/phpsocket.io#142]
`phpsocket.io` 做为客户端这种应用场景也是有的，希望添加这个功能

**Comment by walkor** [comment]
作为socket.io客户端么？

**Comment by 961900832** [comment]
对，是的。有一个应用场景是需要在A服务器中接收B服务器的数据。如果B服务器用的`socket.io`，需要A服务器做为客户端接收。

**Comment by walkor** [comment]
了解，不过这个不属于phpsocket.io该做的事情。如果要实现，得新建个类似phpsocket.io-client得项目

**Comment by 961900832** [comment]
ok，晓得了
