### ISSUE TITLE
There is a recommended way to execute certain actions on server shutdown? 

### ISSUE THREAD

**Issue by LuckyCyborg** [walkor/phpsocket.io#143]
I know it is more related to Workerman, but this bussiness should be done by the SocketIO server somehow.

Imagine that the SocketIO server collects some real-time statistics (saved in memory), because I do not want database requests for every socket event.

BUT, this data should be preserved on server reboot, then I thought to a way to detect the shutdown event and to execute a shutdown procedure, saving the precious information in a database, from where it is reloaded within next boot.

Is there a recommend way for the SocketIO server to know that its Worker(man) is about to shutdown and it to do particular things?

Ideally is something like a "shutdown now" event/callback able to be heard/executed when everything is still up and running, precisely before the Workerman push the kill switch for real.

**Comment by walkor** [comment]
Unfortunately PHPSocketIO does not support any  "shutdown now" callback.
I think the current solution is to use the ```register_shutdown_function``` function.

**Comment by LuckyCyborg** [comment]
Well, looks that's more simple than we thought, thanks to your brilliant design of Workerman. :smirk:

We have the tool, and it do properly the job I expect from, only that the feature was not exposed.

Please consider this small pull request: https://github.com/walkor/phpsocket.io/pull/144

It permit doing something like:
```php
$socketIo->on('workerStop', function ()
{
    // The SocketIO instance is still up and running. We will save the statistics.
});
```
