### ISSUE TITLE
How can I set multiple ssl certificate in Worker Thread?

### ISSUE THREAD

**Issue by willowTank** [walkor/phpsocket.io#148]
Hello I am using this repo in my game server.
It is working with multi-domain. But I want to force https from http.
But I can set only one certificate in a Worker thread.
How can I solve this problem?
I want input multipule certificate in a server
Best Regards

**Comment by walkor** [comment]
Phpsocket.io does not support multiple ssl certificate.
But I think you can use nginx as ssl proxy.

**Comment by willowTank** [comment]
If we use proxy Can I get cookie from requests?
