### ISSUE TITLE
SSL Wrong Version Number Error

### ISSUE THREAD

**Issue by willowTank** [walkor/phpsocket.io#149]
Hello I have set SSL certificate and key file.
But I got 
`
> "error:1408F10B:SSL routines : SSL3_GET_RECORD:wrong version number in ../TcpConnection.php on line 539"`
Please help me

**Comment by walkor** [comment]
Can you show your codes of ssl section?

**Comment by willowTank** [comment]
okay thanks

```
$context = array(
    'ssl' => array(
        //'local_cert' => "C:/xampp/apache/conf/ssl.crt/server.crt",
        //'local_pk'   => "C:/xampp/apache/conf/ssl.key/server.key",
        'local_cert' => Utillity::get_certFilePath(),
        'local_pk'   => Utillity::get_keyFilePath(),
        'verify_peer' => false,
        'allow_self_signed' => true,
        'verify_peer_name' => false,

    )
);
$io = new SocketIO(Utillity::get_gameServerPort(), $context);
```
php 5.4.8

**Comment by willowTank** [comment]
"SSL_CERT":"C:/xampp/apache/conf/ssl.crt/server.crt",
    "SSL_PK":"C:/xampp/apache/conf/ssl.key/server.key"

**Comment by walkor** [comment]
Try to upgrade php to version php5.5 or higher.

**Comment by walkor** [comment]
Do you using cloudflare? 
I got 400 when visit https://ggtt.atm56.net:8080/socket.io/?EIO=3&transport=polling&t=ME8QmUE.
![image](https://user-images.githubusercontent.com/6073368/40372294-ee50a4cc-5e16-11e8-9c1d-c8a1ef9b0ab5.png)
I think this is not phpsocket.io's issue.

**Comment by willowTank** [comment]
right

**Comment by willowTank** [comment]
Should I open the port in ClouldFlare?

**Comment by walkor** [comment]
I am not good at using ClouldFlare, you can ask for help from their customer service.

**Comment by willowTank** [comment]
Thanks a lot

**Comment by walkor** [comment]
You are welcome.
