### ISSUE TITLE
SSL_R_NO_SHARED_CIPER error

### ISSUE THREAD

**Issue by willowTank** [walkor/phpsocket.io#150]
Hello 
Now I have changed my server.
I cancelled CloundFlare.
But I got this error.
Please help me

**Comment by willowTank** [comment]
![capture](https://user-images.githubusercontent.com/24641385/40430251-08dc97f4-5ea5-11e8-83e4-ff63e95a8440.PNG)

**Comment by walkor** [comment]
Please check whether the file exists for ```$context['ssl']['local_cert'] and $context['ssl']['local_pk']``` and the domain of the certificate is matched.
