### ISSUE TITLE
How to emit events as client?

### ISSUE THREAD

**Issue by jakepery6** [walkor/phpsocket.io#155]
Can somebody explain me how you can rewrite this code using this PHP lib:

`import openSocket from 'socket.io-client'; 
const socket = openSocket('http://localhost:8000');
socket.emit('someEvent', {data: cData});`

So here, I simply want to emit event to my server but I'm struggling to do it with PHP.
Any help is appreciated.

**Comment by LuckyCyborg** [comment]
BTW, you look in the wrong garden. :smirk: 

Because this repository is for the PHPSocketIO server implementation, while you really want a client side emitter, like https://github.com/walkor/phpsocket.io-emitter which gives you something like:
```php
$emitter = new Emitter();
$emitter->in('one room')->emit('newmsg', 'hello');
$emitter->emit('newmsg', array('type'=>'blog','content'=>'.....'));
```
