### ISSUE TITLE
Run server.php as linux service

### ISSUE THREAD

**Issue by atukilham** [walkor/phpsocket.io#156]
Thanks for your work, it's very useful for me.
I have a question,
I want to run server.php as service in centos, so if sometime my server was down or reboot, i dont need run execute `php server.php start -d` manually. Just create as service and run in background automatically.
I've tried but the service not run..
Here my service script : 
```
[Unit]
Description=PHP SocketIo service
After=mariadb.service

[Service]
Restart=always
RestartSec=10
User=root
ExecStart=/usr/bin/php /var/www/html/my_app/server.php start -d

[Install]
WantedBy=multi-user.target
```

Anyone can help me?

**Comment by AndrewSologor** [comment]
You can look at my config described here https://github.com/walkor/Workerman/issues/312

Also you may want to allow non-root users to run your service:
```
sudo visudo -f /etc/sudoers.d/socketio
```
Paste next two lines:
```
Cmnd_Alias SOCKETIO_SERVICE_CMNDS = /bin/systemctl start socketio.service, /bin/systemctl stop socketio.service, /bin/systemctl restart socketio.service, /bin/systemctl status socketio.service
%nobody ALL=(ALL) NOPASSWD: SOCKETIO_SERVICE_CMNDS

```
> Replace commands to what you need
Leave last line empty and save the file.
