### ISSUE TITLE
Can I get a socket from io server by socket id ?

### ISSUE THREAD

**Issue by magacyc** [walkor/phpsocket.io#157]
Hello there, I'm new to socket.io.
I know 
`$socket->emit` means sending event to client,
and 
`$io_server->emit` means sending event to all clients;

Is there a way like
`$io_server->getSocketById($socket_id)->emit`
sending event to a specific client ?

**Comment by AndrewSologor** [comment]
`$io_server->sockets->connected['id_here']`

**Comment by devyaz** [comment]
first you have to find a way of storing the id of connected users, i'll use memory in this example
```
$io->on('connection', function($socket){
global $Id;  
     $sid=$socket->id;   //each connection has a unique id this is the currently connected user
     $Id[$sid]=$sid; // add it to the global store(array in memory)
     //then find your own way of getting that users id from array and send
$socket->emit[$sid]('message', DataToSend):   
});```
