### ISSUE TITLE
Enable SSL Webserver in PHP with Workerman and Socket.io

### ISSUE THREAD

**Issue by SilvioLuis** [walkor/phpsocket.io#159]
Hello!

I'm having trouble making my Webserver + Socket work on linux server. In my localhost it works perfectly, but on my server (with SSL) it has some errors:

I put a question in Stackoverflow: https://stackoverflow.com/questions/51068701/enable-ssl-webserver-in-php-with-workerman-and-socket-io

**Comment by SilvioLuis** [comment]
Ok! I started the server and it looks like this:

![captura de tela 2018-06-28 as 11 08 51](https://user-images.githubusercontent.com/6088371/42039466-cea3cbd0-7ac3-11e8-9df0-f6528bf40db1.png)

**Comment by walkor** [comment]
First Socket.io client side should connect port 2020 not 2021.
Second I can't connect to your 2020 port maybe iptables not allowed.

**Comment by SilvioLuis** [comment]
My Socket.io Client:
`var socket = io('https://dev.edufy.com.br:2020', {secure: true});`
we release the port :2020 through the firewall

When i access my client page: 
![captura de tela 2018-06-29 as 17 08 12](https://user-images.githubusercontent.com/6088371/42112715-21a54240-7bbf-11e8-9697-e0eaba59fdec.png)

**Comment by walkor** [comment]
Socket.io client.
```javascript
var socket = io('https://dev.edufy.com.br:2020', {secure: true});
```
I workers fine for me.
![image](https://user-images.githubusercontent.com/6073368/42121239-de8dc0b4-7c5d-11e8-99db-b2763c3ee2e4.png)

**Comment by SilvioLuis** [comment]
I did a simple test with the code below and it still did not work


`<script type="text/javascript" src="vendor/workerman/phpsocket.io/examples/chat/public/socket.io-client/socket.io.js"></script>
<script>
	var socket = io('https://dev.edufy.com.br:2020', {secure: true});
</script>`


https://dev.edufy.com.br/admin/test/chat/test-index.php

**Comment by SilvioLuis** [comment]
Thank you!!! I removed these lines and it worked !!
