### ISSUE TITLE
Hi, walkor, Have you planned to complete the namespace?

### ISSUE THREAD

**Issue by kaysen139** [walkor/phpsocket.io#163]
Now I want to get all the sockets in a room, and I have found it in sokect.io api, It's
```node
io.of('/').in('1234').clients((error, clients) => {
  if (error) throw error;
  console.log(clients); // => [PZDoMHjiu8PYfRiKAAAF, Anw2LatarvGVVXEIAAAD]
});
```

But It has the error like this
```
Error: Call to undefined method PHPSocketIO\DefaultAdapter::clients() in /home/line/data/project/php/study/kf_io/vendor/workerman/phpsocket.io/src/Nsp.php:146
```

So Can anyone tell me what to do now? Thank you very much

**Comment by walkor** [comment]
This looks like a new feature of socket.io.
Phpsocket.io not support that and there is no plan to implement it at the moment.
If anyone can achieve it, I will be very grateful.

**Comment by LuckyCyborg** [comment]
Well, into `PHPSocketIO\Nsp` exists
```php
     public function clients($fn)
    {
        $this->adapter->clients($this->rooms, $fn);
        return $this;
    }
```
BUT the `clients()` does not exists in the `PHPSocketIO\DefaultAdapter`

Looks like it is not a new feature of socket.io, at least it was existent while you grabbed its API, but the implementation is incomplete.

True, someone interested can implement fully this feature, I do not think is so complicated. :smirk:

**Comment by kaysen139** [comment]
Thanks for the replies, I'll find other solutions, like saving records to redis everytime a socket joins in a room.

**Comment by kaysen139** [comment]
At last, I found It's very simple to achieve it. Just need to add a function in DefaultAdapter
```php
    public function clients($rooms, $fn) {
        $sids = array();
        foreach ($rooms as $room) {
            $sids = array_merge($sids, $this->rooms[$room]);
        }
        var_export($sids);
        $fn();
    }
```

**Comment by kaysen139** [comment]
Sorry, The code need some changes:
```php
public function clients($rooms, $fn) {
        $sids = array();
        foreach ($rooms as $room) {
            if (isset($this->rooms[$room]))
                $sids = array_merge($sids, $this->rooms[$room]);
        }
        $fn(array_keys($sids));
    }
```

and in Nsp.php
```php
public function clients($fn)
    {
        $this->adapter->clients($this->rooms, $fn);
        $this->rooms = array();
        $this->flags = array();;
        return $this;
    }
```

**Comment by walkor** [comment]
Please send pull request.
Thanks.

**Comment by LuckyCyborg** [comment]
@kaysen139 

I look suspicious at the Nsp modification, because it will clear the rooms registered in Nsp...

You are pretty sure that that should do this `clients()` ?

**Comment by kaysen139** [comment]
I'm nearly sure that we should clear rooms and flags, because everytime we use **$io->in('room a')->clients()**, 
it will add a room to $this->rooms, and it will influence next operation if we don't clear it, and I've reference   the function emit in Nsp.php
```php
public function emit($ev = null)
{
    $args = func_get_args();
    if (isset(self::$events[$ev]))
    {
        call_user_func_array(array(__CLASS__, 'parent::emit'), $args);
    }
    else
    {
        // set up packet object

        $parserType = Parser::EVENT; // default
        //if (self::hasBin($args)) { $parserType = Parser::BINARY_EVENT; } // binary

        $packet = array('type'=> $parserType, 'data'=> $args );

        if (is_callable(end($args)))
        {
            echo('Callbacks are not supported when broadcasting');
            return;
         }

         $this->adapter->broadcast($packet, array(
             'rooms'=> $this->rooms,
             'flags'=> $this->flags
         ));

        $this->rooms = array();
        $this->flags = array();
    }
    return $this;
}
```
As for I use **array_keys($sids)** , it's because that the structrue just likes **{"ajfdalkjdsfakdfasdfadsf": true}** and I want to get the socket id.

**Comment by LuckyCyborg** [comment]
True. Then, in this case, I guess is better this
```php
    public function clients($rooms, $fn) {
        $sids = array();
        foreach ($rooms as $room) {
            if (isset($this->rooms[$room]))
                $sids = array_merge($sids, array_keys($this->rooms[$room]));
        }
        call_user_func($fn, $sids);
    }
```
Merging over numeric keys will be faster and overall, the memory footprint will be smaller. :smirk: 

Talking about cleaninng rooms and flags, I am still not sure that is needed. Maybe @walkor could enlight us.

**Comment by kaysen139** [comment]
You guys are so addicted to the code.
I have a lot to learn (^_^)
