### ISSUE TITLE
wss

### ISSUE THREAD

**Issue by bluebird89** [walkor/phpsocket.io#164]
use example/chat, up  server, give following tips  

SSL handshake error: stream_socket_enable_crypto(): SSL_R_NO_SHARED_CIPHER: no suitable shared cipher could be used.  This could be because the server is missing an SSL certificate (local_cert context option)

**Comment by walkor** [comment]
It looks like the SSL configuration problem.
Please check the `local_cert` and `local_pk` option.

**Comment by bluebird89** [comment]
thanks, it's about port question
