### ISSUE TITLE
Daemon mod not working

### ISSUE THREAD

**Issue by jet174** [walkor/phpsocket.io#165]
Hi, phpsocket.io in debug in mode works well, in daemon mode not working (do not connect).

> Workerman[chat.php] status
----------------------------------------------GLOBAL STATUS----------------------------------------------------
Workerman version:3.5.11          PHP version:7.2.7-1+ubuntu18.04.1+deb.sury.org+1
start time:2018-08-15 17:56:52   run 0 days 0 hours
load average: 0, 0, 0            event-loop:\Workerman\Events\Select
1 workers       1 processes
worker_name  exit_status      exit_count
PHPSocketIO  0                0
----------------------------------------------PROCESS STATUS---------------------------------------------------
pid     memory  listening               worker_name  connections send_fail timers  total_request qps    status
10210   2M      socketIO://0.0.0.0:8181 PHPSocketIO  3           0         1       5             0      [idle]
----------------------------------------------PROCESS STATUS---------------------------------------------------
Summary 2M      -                       -            3           0         1       5             0      [Summary]

**Comment by walkor** [comment]
Show your codes

**Comment by jet174** [comment]
> <?php
header('Content-Type: text/html; charset=utf-8');
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: GET, POST, PATCH, PUT, DELETE, OPTIONS');
header('Access-Control-Allow-Headers: Origin, Content-Type, X-Auth-Token');
use Workerman\Worker;
use Workerman\WebServer;
use Workerman\Autoloader;
use PHPSocketIO\SocketIO;

// composer autoload
require_once __DIR__ . '/socket/vendor/autoload.php';

include "class/chat_db.php";

$ChatSession = new ChatSession();

const idAdmin = 7;

$vLocked = false;
$vMsg = "";
$context = array(
    'ssl' => array(
         'local_cert' => '/etc/letsencrypt/live/lk.***.ru/cert.pem',
         'local_pk' => '/etc/letsencrypt/live/lk.***.ru/privkey.pem',
        'verify_peer' => false,
    )
);

$io = new SocketIO(8181, $context);

$io->on('connection', function($socket){

  $socket->on('login_vxod', function ($data)use($socket){
		global $ChatSession;
    global $vLocked;
    global $vMsg;
		$users = array();


    $socket->emit('blocked',array("msg" => $vMsg, "on_off" => $vLocked));


		$check = $ChatSession->ChatCheckPrava($data);

		if($check->admins == 1){

			$users = $ChatSession->ChatGetMessageSelect($check->login);

			$socket->uid = idAdmin;
			$socket->join(idAdmin);
		}else{

			$socket->uid = $ChatSession->CheckUserId($check->login);
			$socket->join($ChatSession->CheckUserId($check->login));
		}


      $socket->emit('panel_chat_view', array(
            'chat'=> $check->admins,
			       'users' => $users
      ));

		if($check->admins == 0){

			$chat = $ChatSession->ChatSelectAll($socket->uid , idAdmin);

			if(count($chat) == 0){

				$chat = array(
					"text" => "Здравствуйте, вас привествует служба поддержки вы можете задать интересующий вас вопрос!",
					"dates" => time(),
					"type" => false
				);

			}

			$socket->emit('new All msg',$chat);


		}

	});

	$socket->on('All Msg', function ($data)use($socket){
			global $ChatSession;

			$chat = $ChatSession->ChatSelectAll($socket->uid, $data);

			$socket->emit('new All msg',$chat);

	});

  $socket->on('Blocked', function ($data)use($socket){
			global $ChatSession;
      global $vLocked;
      global $vMsg;
          $vLocked = $data["checked"];
          $vMsg = $data["msg"];
          $socket->broadcast->emit('blocked',array("msg" => $vMsg, "on_off" => $vLocked));
	});


	 $socket->on('msg send', function ($data)use($socket){
			global $ChatSession;
			global $io;



			if(empty($data["sendId"]) or $data["sendId"] == 0){
				$data["sendId"] = idAdmin;
			}

      $data["message"] = empty($data["message"]) ? "" : $data["message"];

      $files = empty($data["files"]) ? "[]" : $data["files"];



			$chat = $ChatSession->ChatAddMessage($socket->uid, $data["sendId"], $data["message"], $files);
			$io->in($socket->uid)->emit('new msg', $chat);

			$chat["type"] = false;
			$io->in($data["sendId"])->emit('new msg', $chat);
			$io->in($data["sendId"])->emit('notifi', idAdmin);


			$ChatSession->Push("У вас новое сообщения", array(
				$ChatSession->CheckUserLogin($data["sendId"])
			));

    

	 });




});

Worker::runAll();

**Comment by walkor** [comment]
Try the codes.
```php
<?php
use Workerman\Worker;
use Workerman\WebServer;
use Workerman\Autoloader;
use PHPSocketIO\SocketIO;

// composer autoload
require_once __DIR__ . '/socket/vendor/autoload.php';

const idAdmin = 7;

$vLocked = false;
$vMsg = "";
$context = array(
    'ssl' => array(
         'local_cert' => '/etc/letsencrypt/live/lk.***.ru/cert.pem',
         'local_pk' => '/etc/letsencrypt/live/lk.***.ru/privkey.pem',
        'verify_peer' => false,
    )
);

$io = new SocketIO(8181, $context);
$io->on('workerStart', function()use($io) {
    include "class/chat_db.php";
    global $ChatSession;
    $ChatSession = new ChatSession();
});
$io->on('connection', function($socket){ ...
```

**Comment by jet174** [comment]
Many thanks!

**Comment by walkor** [comment]
You are welcome.
