### ISSUE TITLE
file_get_contents or PDO not working

### ISSUE THREAD

**Issue by do-web** [walkor/phpsocket.io#166]
Why this does not work? And how can i get it to work?

```
$socket->on('auth', function ($sid, $token) use ($that) {
$user = $that->loadUserFromDb();
$test = file_get_contents('http://localhost');
});
```

**Comment by do-web** [comment]
Yes i tried before my post, it goes only until echo "auth triggered\n"; then it stops without error.
if i try only file_get_content it goes until before file_get_content and then stops.

**Comment by walkor** [comment]
Use ```strace -ttp pid``` to see what happen.
pid is the pid of phpsocket.io which can be found in output for `php start.php status`.

**Comment by LuckyCyborg** [comment]
@do-web 

The greatest issue on using PDO on a PHPSocketIO server is that PDO is not supposed to run all time around the clock.

PDO was made for HTTP side of PHP, then to work in short lived requests.

Long story short, the PDO will easily lose its database connection and will go nuts.

So, you need something more complex, like a class wrapper for database, which auto reconnect to database server when is needed.

**Comment by do-web** [comment]
ok, i have change the logic that i do not need a db connection
