### ISSUE TITLE
Leaving a room not working

### ISSUE THREAD

**Issue by do-web** [walkor/phpsocket.io#167]
Socket 1 and Socket 2. are in the same room.

Socket 1. call $socket->leave('test');
Socket 2. call $socket->leave('test');
Socket 1. call $socket->join('test');

Then Socket 2. received a message:
$io->to('test')->emit('user-joined', $socket->id);

But Socket 2. has leaved the room.

**Comment by walkor** [comment]
Can you provide a demo?

**Comment by do-web** [comment]
Solved my problem :)

**Comment by tihoho** [comment]
@do-web where found bug? it help for other users

**Comment by do-web** [comment]
It was my problem, so wrong server logic
