### ISSUE TITLE
Size of data limit ?

### ISSUE THREAD

**Issue by LorDo** [walkor/phpsocket.io#168]
I'm trying to send large data (SERVER -> CLIENT), and I get the following errors:

socket socket close with reason: "transport close" +2ms
manager onclose +4ms
manager cleanup +0ms
insocket close (transport close) +4ms

Then a reconnect occurs and my data is not delivered to the user.
BUT! If you reduce the data, the data is successfully delivered to the user.
Then I decided to find out what is the maximum limit of the data length, and installed on the server only 1 line:

$socket->emit('test-size', array('value' => bin2hex(openssl_random_pseudo_bytes($SIZE))));

Experienced, I found out that with the value $ SIZE = 1024 * 6 + 700, the data is successfully transmitted.
BUT! If you set $ SIZE = 1024 * 6 + 700 **+ 1**, then the client displays the errors that I wrote above.

Question! Is this really the limit / limit of socket.io or phpsocket.io? Can not I send more size data?

I am use
phpsocket.io 1.1.9
Workerman 3.5.14
PHP version 5.6.32
workerman/channel 1.0.5
socket.io 2.1.1

**Comment by LorDo** [comment]
I spent a very long time debugging and I honestly do not know why this works but it all worked after this fix:

https://github.com/walkor/Workerman/blob/b6162f6cd8579f7bc9959048e8326f1e4ecfaed6/Connection/TcpConnection.php#L694

In this line i am add 1 int to length
Like this:

    $len = fwrite($this->_socket, $this->_sendBuffer, 8192+1);

After that, it all worked! Socket began to send any size, much more tested.

**Comment by walkor** [comment]
https://bugs.php.net/bug.php?id=72333
It looks like a bug for PHP which fixed in 7.1.4 and 7.0.18.

8192 works fine for me but 8192+1 there are problems for me.
