### ISSUE TITLE
How to get a callback when the client confirmed the message reception

### ISSUE THREAD

**Issue by jayHuang332** [walkor/phpsocket.io#17]
I want to use the function in this link: [Sending and getting data (acknowledgements)](http://socket.io/docs/#sending-and-getting-data-(acknowledgements)). 

This link show how this work in node.js, I was wonder how to use fn like blow in PHP:
```
var io = require('socket.io')(80);

io.on('connection', function (socket) {
  socket.on('ferret', function (name, fn) {
    fn('woot');
  });
});
```

**Comment by walkor** [comment]
Unfortunately, it does not support this feature.
