### ISSUE TITLE
Problem with self-signed certificate

### ISSUE THREAD

**Issue by t3mnikov** [walkor/phpsocket.io#171]
Hi. I try to set the certificate but get an error.

`SSL handshake error: stream_socket_enable_crypto(): Unable to set private key file /absolute/path/to/server.key'
`

```
 $context = array(
            'ssl' => array(
                'local_cert'  => '/absolute/path/to/server.pem',
                'local_pk'    => '/absolute/path/to/server.key',
                'verify_peer' => false,
            )
        );
$this->io = new SocketIO($this->port, $context);

```

**Comment by walkor** [comment]
Try to set `$context['ssl']['allow_self_signed'] = true;` and restart phpsocket.io.
If that not working please to take a certificate in for free in https://certbot.eff.org/.
