### ISSUE TITLE
Fatal error: Access to undeclared static property...

### ISSUE THREAD

**Issue by blogdaren** [walkor/phpsocket.io#175]
https://github.com/walkor/phpsocket.io/blob/f2488089e52c8ef57b05aab6d9ef1f7aa2b675ab/src/Engine/Protocols/SocketIO.php#L18

1、well, i found that workerman core has some codes merged which cause the error listed above, see:
https://github.com/walkor/Workerman/commit/dfbbfdd114b9f995f9f77c7516532c766bc4b6ed

2、someone met this problem:  https://wenda.workerman.net/question/3412
meanwhile, some other official projects may be also affected  

3、i guess it shoud change ` TcpConnection::$maxPackageSize`  to `$connection->maxPackageSize `

**Comment by walkor** [comment]
Fixed. Thanks a lot. 👍

**Comment by blogdaren** [comment]
> Fixed. Thanks a lot.

that's ok~
