### ISSUE TITLE
Web and IO server on the same port

### ISSUE THREAD

**Issue by eugene-manuilov** [walkor/phpsocket.io#181]
Hi @walkor 

is it possible to run `WebServer` and `SocketIO` on the same port (for example, on `8080`) but make io work on a subdirectory (for example, `/socket.io`)? Thanks in advance!

**Comment by walkor** [comment]
You can use nginx+php-fpm to run as webserver, and use nginx proxy to redirect socket.io request to phpsocket.io. Here is an nginx config example. 
```
server {
  listen 80;

  location /socket.io
  {
    # Suppose phpsocket.io listens on port 8080.
    proxy_pass http://127.0.0.1:8080;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header X-Real-IP $remote_addr;
  }

  # location / {} ....
}
```

**Comment by eugene-manuilov** [comment]
Ok, thank you.
