### ISSUE TITLE
Connect to a different host

### ISSUE THREAD

**Issue by ongyen8888** [walkor/phpsocket.io#189]
Hi, I saw the sample code for connecting to the socket server but if I want to connect to a remote server, how I can do that?
$io = new SocketIO(2021);

**Comment by alissonpelizaro** [comment]
I have the same issue.
Is it possible to connect e and receive data from other host?

**Comment by walkor** [comment]
Sorry.
This project is server side of socket.io  it can not connect to other host as client.
