### ISSUE TITLE
trouble with install

### ISSUE THREAD

**Issue by manirac** [walkor/phpsocket.io#19]
I installed by php composer.phar install with composer.json found on github.
when I start server.php, I obtain the following message : 
"_Class 'Workerman\PHPSocketIO\SocketIO' not found in  ....server.php at line xx_"
Any idea ??

**Comment by walkor** [comment]
https://github.com/walkor/phpsocket.io/blob/master/examples/chat/server.php
Try this example, maybe that will help.

**Comment by manirac** [comment]
solved the problem by removing all and reinstalling with the following composer.json : 
{
    "require": {
        "workerman/workerman" : ">=3.1.8",
        "workerman/channel" : ">=1.0.0",
        "workerman/phpsocket.io" : ">0.0"
    }
}

**Comment by AndrewSologor** [comment]
Had the same problem. Solved by adding next lines:

```PHP
require_once dirname(__DIR__) .  '/vendor/workerman/workerman/Autoloader.php';
require_once dirname(__DIR__) .  '/vendor/workerman/phpsocket.io/src/autoload.php';
```

PS: 'composer dump-autoload' doesn't help
