### ISSUE TITLE
Is this correct code ?

### ISSUE THREAD

**Issue by uitlaber** [walkor/phpsocket.io#199]
https://github.com/walkor/phpsocket.io/blob/1cde5b1858e38f7bcebb033cfdc06418bf205887/src/ChannelAdapter.php#L61-L64

Is this correct code ?
I have warning Undefined variable: room in file ....\vendor\workerman\phpsocket.io\src\ChannelAdapter.php on line 63

**Comment by walkor** [comment]
This codes means when $this->rooms[$room] is an empty array then  it.

There is no error for unsetting a non-existing variable for php . Can you show me the output for command `php -v` ?

**Comment by uitlaber** [comment]
PHP 7.3.5

**Comment by uitlaber** [comment]
But all working fine in windows!
And i upload to ubuntu server my plugin and try start 
php artisan chat:server start 
output:
```
php artisan chat:server start
Unknown command: chat:server
Usage: php yourfile <command> [mode]
Commands:
start           Start worker in DEBUG mode.
                Use mode -d to start in DAEMON mode.
stop            Stop worker.
                Use mode -g to stop gracefully.
restart         Restart workers.
                Use mode -d to start in DAEMON mode.
                Use mode -g to stop gracefully.
reload          Reload codes.
                Use mode -g to reload gracefully.
status          Get worker status.
                Use mode -d to show live status.
connections     Get worker connections.
```
