### ISSUE TITLE
error on start socket

### ISSUE THREAD

**Issue by sajad-deris** [walkor/phpsocket.io#2]
hi. 
i  when start the app , i got this error in command line:
![error](http://s3.picofile.com/file/8224215450/Capture.PNG)

please help me... :(

**Comment by walkor** [comment]
You can use this repo.
https://github.com/walkor/phpsocket.io-for-win

1. Git clone https://github.com/walkor/phpsocket.io-for-win
2. Run composer install
3. Enter examples/chat directory, and then double-click start_for_win.bat.

Good luck.
