### ISSUE TITLE
deploy on shared host

### ISSUE THREAD

**Issue by erfanhemmati** [walkor/phpsocket.io#219]
hey guys...
how i can deploy the chat example into the shared host ?

**Comment by walkor** [comment]
Sorry, phpsocket.io not support shared host.

**Comment by erfanhemmati** [comment]
@walkor 
ok. can we deploy phpsocket.io in dedicated server such as centos ?

**Comment by erfanhemmati** [comment]
@walkor thanks for your help.

**Comment by walkor** [comment]
Yes


发自我的iPhone

------------------ Original ------------------
