### ISSUE TITLE
xhr poll error

### ISSUE THREAD

**Issue by manirac** [walkor/phpsocket.io#22]
I wrote a very simple application to test communication between nodeJS and PHP.
Here's my code PHP (server side) :

`include **DIR** . '/../vendor/autoload.php';
use Workerman\Worker;
use Workerman\WebServer;
use Workerman\Autoloader;
use PHPSocketIO\SocketIO as Socket;

$io = new Socket(8000);

$io->on('connection', function($socket) {
    echo ('new connection');
    $socket->addedUser=false;
    $socket->on('EVT1', function ($data) use ($socket){
        vardump($data);
        $socket->emit('ACK1', array('message'=>'EVT1 flushed'));
    });
    $socket->on('EVT2',function ($data) use ($socket){
        $socket->emit('ACK2', array('message'=>'EVT2 flushed'));
    });
});

$web = new WebServer('http://0.0.0.0:8002');
$web->addRoot('localhost', **DIR** . '/public');
Worker::runAll();`

Here's the code on the client side (nodeJS) :

`var io = require('socket.io-client');
socket = io.connect('localhost', {
    port: 8000,
    reconnection : true
});
socket.on('connect', function () { console.log("socket connected"); });
socket.on('connect_error', function(err) {console.log('connection error :'+err.message)});
socket.emit('EVT1', { user: 'me', msg: 'whazzzup?' });
socket.on('ACK1',function(data){console.log('received info : '+data);});`

I obtain the following result : `connection error : xhr poll error`

Any idea ??

**Comment by walkor** [comment]
May be syntax error in your codes.
```php
vardump($data);
```

You can run phpsocket.io as debug mode with command ```php yourfile.php start```. No -d. You can see all error messages in terminal then, include syntax error.

**Comment by manirac** [comment]
Tried whet you suggested. Problem seems to be before connection.
nodejs client seems unable to find websocket from phpsocket.io (when I start it without launching php server, I obtain the same error). Is it possible to rule options in phpsocket (like protocols and so one...) ?

**Comment by walkor** [comment]
Iptables?

**Comment by manirac** [comment]
all policies to ACCEPT

**Comment by manirac** [comment]
I modified the code on the client's side :

`var io = require('socket.io-client');
socket = io.connect('http://localhost:8000',{reconnect:true});
socket.on('connect', function (data) { 
    console.log("client connecté");
    this.emit('EVT1','EVT1 envoyé au serveur');
    this.on('ACK1',function(data){
        console.log('données reçues : '+data);
        socket.disconnect(function() {console.log('Disconnect')});
    });    
});
socket.on('connect_error', function(err) {
    console.log('erreur de connexion :'+err.message)
});`

This works fine corresponding with a server built on nodeJs too. 

When I try to communicate with the server built on PHP with phpsocket.io, the server logs "new connection", but the client does not say nothing. It seems the events socket.on, on the client side, is not fired.

Did i forget something ??

**Comment by walkor** [comment]
hmm, may be phpsocket.io not compatible with socket.io-client.

**Comment by manirac** [comment]
L'm sorry, but that's you use to built your chat example. The socket.io-client is on the client side on the main.js file. Is n't it ??

**Comment by walkor** [comment]
Yes, socket.io-client works in browser. I have no idea what is the problem with nodejs.

**Comment by manirac** [comment]
[nodephp.tar.gz](https://github.com/walkor/phpsocket.io/files/297983/nodephp.tar.gz)

Using tcpdump, I sniffed the packets between client nodeJS and server nodeJS, and then the packets between client nodeJS and server PHP. You'll find the result of the captures in the attached file (node_to_node.log and node_to_php.log). You can look at them using wireshark or another similar program. It seems PHP server don't start the second session after initializing the tunnel. Is it a problem linked with the  origin of the packets ? In the attached file, you'll find also the code of the differents modules. Can it be the occasion for you to extend the functionality of phpsocket.io ? Could you have a look on them ??
Thanks in advance.

**Comment by manirac** [comment]
In addition to the previous message, you'll find the TCP stream analysis of the dialog between the node and the client :
node to node :
`GET /socket.io/?EIO=3&transport=polling&t=LKLsh2F&b64=1 HTTP/1.1
User-Agent: node-XMLHttpRequest
Accept: */*
Host: localhost:8000
Connection: close

HTTP/1.1 200 OK
Content-Type: text/plain; charset=UTF-8
Content-Length: 100
Access-Control-Allow-Origin: *
Set-Cookie: io=aH8vtET6H8qfAx2NAAAB
Date: Fri, 03 Jun 2016 10:41:41 GMT
Connection: close

97:0{"sid":"aH8vtET6H8qfAx2NAAAB","upgrades":["websocket"],"pingInterval":25000,"pingTimeout":60000}`

node to php
`GET /socket.io/?EIO=3&transport=polling&t=LKLss5v&b64=1 HTTP/1.1
User-Agent: node-XMLHttpRequest
Accept: */*
Host: localhost:8000
Connection: close

HTTP/1.1 200 OK
Connection: keep-alive
Content-Type: application/octet-stream
Content-Length: 104
X-XSS-Protection: 0
Access-Control-Allow-Origin: *

100:0{"sid":"1464950546.824280615650","upgrades":["websocket"],"pingInterval":25000,"pingTimeout":60000}`

You can see that the response of the server is quite different.

**Comment by walkor** [comment]
Fixed and please try again.

**Comment by manirac** [comment]
Going on the tests. The fix you made is fine, but the server doesn't answer to the EVT1 fired by the client.
I join the entire TCP stream analysis in the mode (nodestream.txt is node to node et phpstream.txt is node to php). on the server side, I obtain the folowwing message : 

> PHP Warning:  Missing argument 1 for PHPSocketIO\Event\Emitter::emit() in /home/developpeur/projets/prcl1600/vendor/workerman/phpsocket.io/src/Event/Emitter.php on line 81

[nodestream.txt](https://github.com/walkor/phpsocket.io/files/298719/nodestream.txt)
[phpstream.txt](https://github.com/walkor/phpsocket.io/files/298720/phpstream.txt)

thanks for all.

**Comment by walkor** [comment]
I test ok, here are the outputs of srv_php.php.
```
utilisateur connecté
reçu EVT1
got disconnect packet
```

**Comment by manirac** [comment]
Fine, that's good, but that does not explain why the srv_php.php program does not respond to the EVT1 it receives.... Did I make an error in it ???
(the "got disconnect packet" comes when you hold ctrl+c on the client side program)

**Comment by dam1r89** [comment]
Hey, just a note: I was getting same PHP Warning message when I was trying to send a huge json object. Pay attention to the data size.

Decoder class was failing to parse half received json string and returned data was null causing further warnings and errors in my application.
