### ISSUE TITLE
Question about authentication middleware

### ISSUE THREAD

**Issue by hinet2013** [walkor/phpsocket.io#226]
Is there some equivalent to the 'use' method?
https://socket.io/docs/server-api/#namespace-use-fn

I need to perform authentication by allowing connection only when a valid token has been provided by the client

I'm already able to submit the token from the client via the `query` option and to retrieve it with `$socket->handshake->query->token` in the `connect` handler but there it's too late (client already connected)

So:
- is there a way to patch the library by allowing some hook mechanism to the handshake phase?
- as alternative: how can i close the connection to the unauthenticated client from the server side?

**Comment by walkor** [comment]
Phpsocket.io not support middleware. I can not tell you how to  to patch.
You can close the unauthenticated client by `$socket->disconnect();`

**Comment by hinet2013** [comment]
Ok i defined some sort of applicative protocol that works in this manner:

- Server always accepts connections (due to the lack of middleware support)
- After successful connection the server checks for the presence of a query argument (that client must have set before connecting) and validates the authToken carried in it. If the verification fails the socket is closed from the server side as you suggest
- In case the validation was successful the server starts a timer that performs the disconnection after the token expiration time has elapsed
- Client application has a renewal agent that periodically obtains a new token and informs the server with `socket.emit`
- Server listens to such client messages and when a new valid token is recevied it stops the previous timer and starts a new one with the new expiration

Hoping to help someone other that will encounter the same situation
