### ISSUE TITLE
Emit php file to PHPSocketIO server.

### ISSUE THREAD

**Issue by Ritchelly** [walkor/phpsocket.io#228]
### Hi, folks!
I'm tryning to communicate  Emit from Client.php file to PHPSocketIO server, but cant't arriving emit message in server, only connection message. I tested by WebBrowser with socket.io and work ok. But when I try to comunicate emit message from client.php to server.php ( I realy need to this process) I no have success.  I tested a lot of examples and ways, but not success. 

I tryed do exampes of #23, but I'm continued without sucess.

**This is My Server Code:**
````
<?php

use Workerman\Worker;
use Workerman\WebServer;
use Workerman\Autoloader;
use PHPSocketIO\SocketIO;

// Composer autoload
include 'vendor/autoload.php';
// =======Channel server========
$channel = new Channel\Server();
$io = new SocketIO(2020);
// ========ChannelAdapter========
$io->on('workerStart', function()use($io){
	echo "workerStart".PHP_EOL; // Only print the data to debug
    $io->adapter('\PHPSocketIO\ChannelAdapter');
});
$io->on('connection', function($socket){
	$socket->addedUser = false;
	echo "connection".PHP_EOL;
	
    // when the client emits 'new message', this listens and executes
    $socket->on('teste', function ($data)use($socket){
	echo "haaaateste{$data}".PHP_EOL;  // Only print the data to debug

        // we tell the client to execute 'new message'
        $socket->broadcast->emit('teste', array(
            'username'=> $socket->username,
            'message'=> $data
        ));
   });
});
Worker::runAll();
````

**And this is file is Emit code: (Don't work)** 

````
<?php
require_once __DIR__ . '/vendor/autoload.php';
$emitter = new Emitter();
$emitter->emit('teste', array('username'=>'test'));
````
**And this is a Elephant Framework, the connect work, but not emit message in server side:**

````
<?php

require 'vendor/autoload.php';

use ElephantIO\Client;
use ElephantIO\Engine\SocketIO\Version2X;

$client = new Client(new Version2X('http://127.0.0.1:2020'));

$client->initialize();
// send message to connected clients
$client->emit('teste', ['asasasdd']);
$client->close();
````

Someone can Help me?

Sorry for my inglish!

Thanks!

**Comment by walkor** [comment]
This codes means to emit `teste` to the client side.
```php
<?php
require_once __DIR__ . '/vendor/autoload.php';
$emitter = new Emitter();
$emitter->emit('teste', array('username'=>'test'));
```

```js
var socket = io('http://127.0.0.1:2020');
socket.on('teste', function(msg){
    console.log(msg);
});
```
Will show the output `{username: "test"}` in browser console.

I don't know the detail for ElephantIO so I can not tell you what the problem with it.

If you want to  communicate  to PHPSocketIO server with your client.php,  you can listen a http port in the PHPSocketIO process like this.

```php
<?php

use Workerman\Worker;
use PHPSocketIO\SocketIO;
use Workerman\Protocols\Http\Request;

// Composer autoload
include 'vendor/autoload.php';
$io = new SocketIO(2020);
$io->on('workerStart', function()use($io){
    // #### Here listen a http port 3030 #####
    $http = new Worker('http://0.0.0.0:3030');
    $http->onMessage = function($http_connection, Request $request){
        global $io;
        $get = $request->get(); 
        $io->emit('teste', array(
            'username'=> $get['username'],
            'message'=> $get['data']
        ));
        $http_connection->send('ok');
    };
    $http->listen();
});
$io->on('connection', function($socket){
	$socket->addedUser = false;
	echo "connection".PHP_EOL;
	
    // when the client emits 'new message', this listens and executes
    $socket->on('teste', function ($data)use($socket){
	echo "haaaateste{$data}".PHP_EOL;  // Only print the data to debug

        // we tell the client to execute 'new message'
        $socket->broadcast->emit('teste', array(
            'username'=> $socket->username,
            'message'=> $data
        ));
   });
});
Worker::runAll();
```

client.php
```
<?php
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, "http://127.0.0.1:3030/?username=tom&data=123");
curl_setopt($ch, CURLOPT_HEADER, 0);
curl_exec($ch);
curl_close($ch);
```

Client.php will send http request to port 3030 which PHPSocket.io listening too and `$http->onMessage` will be fried and you can do any thing with PHPSocket.io server.

**Comment by Ritchelly** [comment]
@walkor Thank you very much! 

Now is working to comunicate the client.php with my socketServer. Thanks :)

Now I'm understanding the logical to emit. He cominicate (emit) only to javascript socket.io, i'm right?
If yes, the first example that you showed for me, don't work. Have you some idea that can be?
I copied your code and executed. But this part don't do nothing. :(

I wanna thankyou and congratulate for project. Is really brilliant. Was much time that I searching for something like this .

**Comment by walkor** [comment]
> Now I'm understanding the logical to emit. He cominicate (emit) only to javascript socket.io, i'm right?

Yes.

> If yes, the first example that you showed for me, don't work. Have you some idea that can be?
I copied your code and executed. But this part don't do nothing. :(

I tested the first example and works well for me.

`composer require workerman/phpsocket.io`
`composer require workerman/phpsocket.io-emitter`

io.php
```php
<?php

use Workerman\Worker;
use Workerman\WebServer;
use Workerman\Autoloader;
use PHPSocketIO\SocketIO;

// Composer autoload
include 'vendor/autoload.php';
// =======Channel server========
$channel = new Channel\Server();
$io = new SocketIO(2020);
// ========ChannelAdapter========
$io->on('workerStart', function()use($io){
	echo "workerStart".PHP_EOL; // Only print the data to debug
    $io->adapter('\PHPSocketIO\ChannelAdapter');
});
$io->on('connection', function($socket){
	$socket->addedUser = false;
	echo "connection".PHP_EOL;
	
    // when the client emits 'new message', this listens and executes
    $socket->on('teste', function ($data)use($socket){
	echo "haaaateste{$data}".PHP_EOL;  // Only print the data to debug

        // we tell the client to execute 'new message'
        $socket->broadcast->emit('teste', array(
            'username'=> $socket->username,
            'message'=> $data
        ));
   });
});
Worker::runAll();
```

client.php
```php
<?php
require_once __DIR__ . '/vendor/autoload.php';
$emitter = new Emitter();
$emitter->emit('teste', array('username'=>'test'));
```

Start io.php like this.
![image](https://user-images.githubusercontent.com/6073368/78234880-61d9ae00-750a-11ea-95f5-fb63bf44591a.png)

Run client.php like this.
![image](https://user-images.githubusercontent.com/6073368/78235049-9d747800-750a-11ea-9204-67733897917a.png)

The client side like this and `{username: "test"}` printed.
![image](https://user-images.githubusercontent.com/6073368/78234620-fe4f8080-7509-11ea-88d0-fe21774a11e8.png)

**Comment by Ritchelly** [comment]
Hi, Sorry for delay for response. I'm here to say that now working perfectly. Thank you very much. I will close this issue.

**Comment by H4mdan90** [comment]
hi there, i still can not arriving emit message in server from cilent php. 
please help
