### ISSUE TITLE
Sending events from php

### ISSUE THREAD

**Issue by ptdev** [walkor/phpsocket.io#23]
Hi there, I'm using a slightly modified version of this project's chat demo.

Now, i have a question: Can I send messages to the chat from a php script or separate php app?

For example: I wanted to send a chat to everybody when something get's stored on the database. (e.g.: "user X has added/modified product Y" type messages)

Thanks

**Comment by walkor** [comment]
Try https://github.com/walkor/phpsocket.io-emitter.

**Chat for server side.**
```php
<?php
use Workerman\Worker;
use Workerman\WebServer;
use Workerman\Autoloader;
use PHPSocketIO\SocketIO;

// Composer autoload
include '/your/path/vendor/autoload.php';

// =======Channel server========
$channel = new Channel\Server();

$io = new SocketIO(2020);
// ========ChannelAdapter========
$io->on('workerStart', function()use($io){
    $io->adapter('\PHPSocketIO\ChannelAdapter');
});
$io->on('connection', function($socket){
    $socket->addedUser = false;

    // when the client emits 'new message', this listens and executes
    $socket->on('new message', function ($data)use($socket){
        // we tell the client to execute 'new message'
        $socket->broadcast->emit('new message', array(
            'username'=> $socket->username,
            'message'=> $data
        ));
    });
..............
```

**Your php script or php app.**
```php
<?php
// composer autoload
include __DIR__ . '/your/path/vendor/autoload.php';
$emitter = new Emitter();
$emitter->emit('new message', array('username'=>'test', 'message'=>'~~~~~~ok~~~~~~'));
```

**Comment by ptdev** [comment]
Hey, thanks a lot for your help. That worked perfectly. 👍 

Good job on this project. Keep it up.

Best regards.

**Comment by vetash** [comment]
Hello! This example does not work for me, can you help me? 
i use this server example:
https://github.com/walkor/phpsocket.io/blob/master/examples/chat/server.php
And trying to send message like that:
```<?php
// composer autoload
include __DIR__ . '/vendor/autoload.php';
$emitter = new Emitter('<MYIPADDR>');
$emitter->emit('new message', array('username'=>'test', 'message'=>'Test'));```

When i run php script above - nothing happens. No errors no nothing.
How can i debug it?

**Comment by ptdev** [comment]
You don't need that ip address when instancing the Emitter class.

Also make sure your server.php is setup like the example gave by @walkor above because his example works fine.

**Comment by vetash** [comment]
@ptdev i.e. emmiter chould connect to `ChannelServer` instead of socket? I mean when i run server there's 2  active ports:
```----------------------- WORKERMAN -----------------------------
Workerman version:3.3.4          PHP version:5.4.45-0+deb7u2
------------------------ WORKERS -------------------------------
user          worker        listen                   processes status
root          PHPSocketIO   socketIO://0.0.0.0:2020   1         [OK] 
root          WebServer     http://0.0.0.0:2022       1         [OK]
```
so if i add chat server i see:
```------------------------ WORKERS -------------------------------
user          worker         listen                   processes status
root          ChannelServer  frame://0.0.0.0:2206      1         [OK] 
root          PHPSocketIO    socketIO://0.0.0.0:2020   1         [OK] 
root          WebServer      http://0.0.0.0:2022       1         [OK] 
----------------------------------------------------------------
```
Why i cant use just `PHPSocketIO` port?

**Comment by ptdev** [comment]
Yes, I believe it does use the channel server. I didn't get too much into the details since the example given to me by @walkor was enough to get my server messages working.

I personally removed the webserver since I'm using it through my existing webserver (nginx) so in my case I only have the ChannelServer and the SocketIO server.

**Comment by vetash** [comment]
@ptdev Ok got it. Thank for the reply!

**Comment by joanebrown** [comment]
When I trying to use the Channel I get the next error:

      Class 'workerman\Channel\Server' not found

I have installed all this packages:

    workerman/channel                     v1.0.3
    workerman/phpsocket.io                v1.1.0
    workerman/phpsocket.io-emitter        v1.0.1
    workerman/workerman                   v3.3.6 

But I don't know what are the imports I need to get it work:

    use Workerman\Worker; /// Yes, neccesary and works.
    use PHPSocketIO\SocketIO; ///  Works.
    //use PHPSocketIO\Channel\Server; // ???
    //use Workerman\Channel\Server; // ???

Where is the class name I need to import??? Thank you :-)

**Comment by walkor** [comment]
```use Channel\Server;```

**Comment by joanebrown** [comment]
Thank you very much @walkor. Now this doesnt show any error... But doesn't work :-S

I have exactly the same as your example, but, when I "trigger" an event from my PHP code (outside the workerman):

    use PHPSocketIO\Event\Emitter;
    $emitter = new Emitter();
    $emitter->emit('myTest', array('message' => 'Test, test, test'));

And, inside workerman:

    $io->on('connection', function($socket) {

         echo "New connection!!!!!!!";

        $JWT = (isset($socket->handshake["query"]["jwt"])) ? $socket->handshake["query"]["jwt"] : null;

         // this funciton will check if the JWT token is valid and return the user, if not will close (disconnect) the socket
        $user= self::checkJWT($JWT, $socket);

        if ($user) {

            $socket->username= $user->username;
            $socket->join("room" . $socket->id);

            $socket->on('myTest', function ($data) use($socket) {
                    echo "\n*** Emitter !!!!!!\n";
                    print_r($data);
            });
        } else {
             echo "\n*** Wrong token\n";
        }

    [...]

But I never see "Emitter !!!!!!!!!!!!" inside my terminal. And FYI, this login system with JWT works well (I tried this without the emitter, using client side to emit and works). Neither I see the "New connection!!!!!!!" when I emit with Emitter, so I think that not fail for the login system... There is any way to debug this issue?

I really appreciate any help

**Comment by walkor** [comment]
PHPSocketIO\Event\Emitter it will not emit server's event but clients.

**Comment by joanebrown** [comment]
Hi @walkor, sorry.. I'm not understand you :-(

    use PHPSocketIO\Event\Emitter;
    $emitter = new Emitter();
    $emitter->emit('myTest', array('message' => 'Test, test, test'));

This will not emit an event "myTest" to the phpsocket.io?

**Comment by joanebrown** [comment]
You mean which when I use:

    use PHPSocketIO\Event\Emitter;
    $emitter = new Emitter();
    $emitter->emit('myTest', array('message' => 'Test, test, test'));

This will emit an "myTest" event to all clients? (I tried now and doesn't work... :-S )

**Comment by walkor** [comment]
Sorry for my poor English.

Your php script.
```php
use PHPSocketIO\Event\Emitter;
$emitter = new Emitter();
$emitter->emit('myTest', array('message' => 'Test, test, test'));
```
Clients side.
```javascript
var socket = io('http://'+document.domain+':3120');
socket.on('myTest', function(){...});
```

That will trigger myTest event of clients side.
That will not  trigger myTest event of server side inside workerman.

**Comment by joanebrown** [comment]
Hi @walkor don't worry about english, my english is worse than yours.

Okey, I understand. But... seems to not work :-S I have exactly the same approach than you shows, but when I execute an HTTP request for:

    use PHPSocketIO\Event\Emitter;
    $emitter = new Emitter();
    $emitter->emit('myTest', array('message' => 'Test, test, test'));

I have no see this in my other browser tab:

    socket.on('myTest', function(data){
        console.log("Trigered!!!!");
        console.info(data);
    });

And when I use:

    php artisan WorkerManTests status

I see:

    ---------------------------------------PROCESS STATUS-------------------------------------------
    pid     memory  listening               worker_name   connections total_request send_fail throw_exception
    5149    13.25M  frame://0.0.0.0:2206    ChannelServer 1           244            0         0
    5150    16.75M  socketIO://0.0.0.0:2005 PHPSocketIO   3           475            0         0

Maybe I have a wrong setup with Laravel? Since I using a laravel command I passing parameters to workerman as follow:

        global $argv;
        $argv[1] = $this->argument('action'); // start, status, stop, ...
        $argv[2] = "-d";

Can you think that it may be happening?

**Comment by joanebrown** [comment]
@walkor My "use" was wrong, sorry :-( I use `use PHPSocketIO\Event\Emitter;` instead of `use Emitter;`

BTW: It's secure to use an channel and a emitter? Can any script connect to my channel outside my webserver and send some events?

**Comment by walkor** [comment]
You can only bind 127.0.0.1 like this.
```php
$channel = new \Channel\Server('127.0.0.1');
```
Then no one can connect to your channel to emit any events outside.

You can also set up your iptables to do that.

**Comment by tolew1** [comment]
@walkor I have a question about this. Do you have to use Channel Adapter for this to work? Or can I just add this to my php file and use this to just send or emit a message to the clients without channel adapter? Like it will just emit to all connect clients on that server?

**Comment by jjchaverra** [comment]
Hi @walkor. I have 

start_io.php

`use Workerman\Worker;
use Workerman\WebServer;
use Workerman\Autoloader;
use PHPSocketIO\SocketIO;
use Channel\Server;

// =======Channel server========
$channel = new Channel\Server('127.0.0.1');
$io = new SocketIO(2020);


// ========ChannelAdapter========
$io->on('workerStart', function()use($io){
    $io->adapter('\PHPSocketIO\ChannelAdapter');
});`

And result (windows):


------------------------ WORKERS -------------------------------
worker         listen                   processes status
ChannelServer  frame://127.0.0.1:2206    1        [OK]
PHPSocketIO    SocketIO://0.0.0.0:2020   1        [OK]
----------------------------------------------------------------
Press Ctrl-C to quit. Start success.
@@@ Error: multi workers init in one php file are not support @@@
@@@ Please visit http://wiki.workerman.net/Multi_woker_for_win @@@

**Comment by jjchaverra** [comment]
Hi @walkor. I have

start_io.php

```use Workerman\Worker;
use Workerman\WebServer;
use Workerman\Autoloader;
use PHPSocketIO\SocketIO;
use Channel\Server;

// =======Channel server========
$channel = new Channel\Server('127.0.0.1');
$io = new SocketIO(2020);

// ========ChannelAdapter========
$io->on('workerStart', function()use($io){
$io->adapter('\PHPSocketIO\ChannelAdapter');
});```

And result (windows):

```
----------------------- WORKERMAN -----------------------------
Workerman version:3.4.5          PHP version:7.1.6
------------------------ WORKERS -------------------------------
worker         listen                   processes status
ChannelServer  frame://127.0.0.1:2206    1        [OK]
PHPSocketIO    SocketIO://0.0.0.0:2020   1        [OK]
----------------------------------------------------------------
Press Ctrl-C to quit. Start success.
@@@ Error: multi workers init in one php file are not support @@@
@@@ Please visit http://wiki.workerman.net/Multi_woker_for_win @@@
```

**Comment by walkor** [comment]
Workerman do not support start multi servers in one file.
Please create a new file to start Channel\Server for windows.
start_channel.php
```php
<?php
use Workerman\Worker;
use Workerman\WebServer;
use Workerman\Autoloader;
use PHPSocketIO\SocketIO;
use Channel\Server;

// =======Channel server========
$channel = new Channel\Server('127.0.0.1');
$io = new SocketIO(2020);
Worker::runAll();
```
And run with command ```php start_io.php start_channel.php```.

**Comment by steffanhalv** [comment]
Hi, just for reference if anyone else was struggling with this like me:

**To get php server to work:**

```bash
composer require workerman/phpsocket.io
```

```php
<?php

// PHP Server

use Workerman\Worker;
use PHPSocketIO\SocketIO;
use Channel\Server;

require __DIR__.'/vendor/autoload.php';

$channel = new Server();
$io = new SocketIO(2021);
$io->on('workerStart', function()use($io){
	$io->adapter('\PHPSocketIO\ChannelAdapter');
});
$io->on('connection', function($socket)use($io){
	// Broadcast all information about new client to all connections (for debugging)
	$io->emit('broadcast', [
			'id' => $socket->id,
			'rooms' => $socket->rooms,
			'request' => $socket->request,
			'handshake' => $socket->handshake
	]);
	// Set server to listen on requests
	$socket->on('request', function($message)use($io, $socket){
		// Send to connector
		$socket->emit('user_message', 'Hello You!');
		// Send to all
		$io->emit('broadcast', 'Hello All!');
		// Send to all except sender
		$socket->broadcast->emit('broadcast', 'New user entered connection');
		// Send to specific user
		$io->to($socket->id)->emit('broadcast', 'Private message');
	});
});
```

**To get php client to work:**

```bash
composer require workerman/phpsocket.io-emitter
```

```php
<?php
// Client

use Emitter; // THIS IS CORRECT!!!
// use PHPSocketIO\Event\Emitter; // THIS IS WRONG!!!

$emitter = new Emitter();
$emitter->emit('test', 'Works!');
```

**To get nodejs client to work:**

```bash
npm i socket.io-client --s
```

```js
import io from 'socket.io-client'

let socket = io('http://localhost:2021')
socket.on('broadcast', data => {
       console.log('Broadcast', data)
})
socket.on('test', data => {
       console.log('Test', data) // Shows 'Works!'
})
socket.emit('request', 'Message sent to server')
```

**Comment by seyitahmettanriver** [comment]
![image](https://user-images.githubusercontent.com/29552284/101306603-67845200-3856-11eb-9fcc-5e0833f39bb7.png)
![image](https://user-images.githubusercontent.com/29552284/101306610-6d7a3300-3856-11eb-8f67-eabf8078e498.png)
![image](https://user-images.githubusercontent.com/29552284/101306625-75d26e00-3856-11eb-9dc1-3bf6bc5cb148.png)
![image](https://user-images.githubusercontent.com/29552284/101306647-8387f380-3856-11eb-9949-014de7674ef6.png)


XAMPP fails in PHP 7.4.

**Comment by seyitahmettanriver** [comment]
> Workerman do not support start multi servers in one file.
> Please create a new file to start Channel\Server for windows.
> start_channel.php
> 
> ```
> <?php
> use Workerman\Worker;
> use Workerman\WebServer;
> use Workerman\Autoloader;
> use PHPSocketIO\SocketIO;
> use Channel\Server;
> 
> // =======Channel server========
> $channel = new Channel\Server('127.0.0.1');
> $io = new SocketIO(2020);
> Worker::runAll();
> ```
> 
> And run with command `php start_io.php start_channel.php`.

Help me

**Comment by ruisen-huang** [comment]
> @walkor My "use" was wrong, sorry :-( I use `use PHPSocketIO\Event\Emitter;` instead of `use Emitter;`
> 
> BTW: It's secure to use an channel and a emitter? Can any script connect to my channel outside my webserver and send some events?

I gave up trying for a few hours, but my eyes lit up when I saw your reply. I know what the problem is, hahahaha
