### ISSUE TITLE
phpsocket.io/src/Engine/Engine.php   Unable to correctly resolve the whitelist of two domain names

### ISSUE THREAD

**Issue by jiaoshengkang** [walkor/phpsocket.io#231]
166-171行：
需要加一个判断，$ok === true 才调用成功回调，全部白名单检查失败，才走默认。

**Comment by walkor** [comment]
https://github.com/walkor/phpsocket.io/blob/d0d046606e52a2e5b72807240930f83cbc59f443/src/Engine/Engine.php#L171

这里 `if ($ok)` 和 `if($ok === true)` 没区别吧
