### ISSUE TITLE
Args updating in parseCommand

### ISSUE THREAD

**Issue by RazaGR** [walkor/phpsocket.io#246]
**1.** I am including this library in my framework, I had to replace args position in `protected static function parseCommand()` method in
`vendor/workerman/workerman/Worker.php`
From 
```
        if (!isset($argv[2]) || !\in_array($argv[2], $available_commands)) {
            if (isset($argv[2])) {
                static::safeEcho('Unknown commandss: ' . $argv[2] . "\n");
            }
            exit($usage);
        }

        // Get command.
        $command  = \trim($argv[2]);
        $command2 = isset($argv[3]) ? $argv[3] : '';
```

TO
```
        if (!isset($argv[3]) || !\in_array($argv[3], $available_commands)) {
            if (isset($argv[3])) {
                static::safeEcho('Unknown commandss: ' . $argv[3] . "\n");
            }
            exit($usage);
        }

        // Get command.
        $command  = \trim($argv[3]);
        $command2 = isset($argv[4]) ? $argv[4] : '';
```

because  it was capturing my controller name at $argv[2], I guess `parseCommand` should be more dynamic?

**2.** secondly, I wanted to know how reliable this library is compared to NodeJS? are there any benchmarks or comparision available? how many connections it can handle?

**Comment by walkor** [comment]
1. Please upgrade workerman to v4.0.11. It support commands more flexible like `php start.php controller_name start ` etc.
2. There is no comparison data with nodejs. Theoretically, this library can support tens of thousands of connections, but this does not mean that any business can support such a large number of connections.

**Comment by RazaGR** [comment]
@walkor Thank you for the fast update on this, regarding commands I think there is another var needs updating, see the last line, after I run command:

**Comment by walkor** [comment]
> btw I noticed the demon commands output wrong info to stop, see the last line.

This is fixed in master and will be released with the next version.
