### ISSUE TITLE
Support for version 3 and above?

### ISSUE THREAD

**Issue by carlo-fontanos** [walkor/phpsocket.io#250]
I am trying to run the client side on version 3: 

```
<script src='https://cdnjs.cloudflare.com/ajax/libs/socket.io/3.0.1/socket.io.min.js'></script>
<script> 
var socket = io("http://" + document.domain + ":2120", {
  transports: ['websocket']
});
</script>
```
But I get the following error on my console: 

![image](https://user-images.githubusercontent.com/12164593/99353773-2a284680-28e0-11eb-9b1e-37b62616a036.png)

Does you PHPSockt.io support version 3?

**Comment by walkor** [comment]
Sorry. Not support socket.io version 3.
