### ISSUE TITLE
Infinite reconnection

### ISSUE THREAD

**Issue by dividerbeam** [walkor/phpsocket.io#256]
Client side:
`var socket = io('https://'+document.domain+'/socket.io/');`

Nginx:
```
location /socket.io/ {
        proxy_pass http://myServerIP:2020/socket.io/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header X-Real-IP $remote_addr;
    }
```
and result:
![socketio](https://user-images.githubusercontent.com/52495131/104383079-47743c80-5540-11eb-8772-b031669dabf6.jpg)

server answer:
`96:0{"sid":"VlC_PZXQOS4w8sowB6Yt","upgrades":["websocket"],"pingInterval":25000,"pingTimeout":5000}`

i think problem with "sid", its not saved after first connect, but i dk how fix that

help plz

**Comment by walkor** [comment]
Try config
```
location /socket.io {
        proxy_pass http://myServerIP:2020;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header X-Real-IP $remote_addr;
    }
```

**Comment by dividerbeam** [comment]
> Try config
> 
> ```
> location /socket.io {
>         proxy_pass http://myServerIP:2020;
>         proxy_http_version 1.1;
>         proxy_set_header Upgrade $http_upgrade;
>         proxy_set_header Connection "Upgrade";
>         proxy_set_header X-Real-IP $remote_addr;
>     }
> ```
> 
> Client side:
> var socket = io('https://'+document.domain);
