### ISSUE TITLE
How to run it on a server

### ISSUE THREAD

**Issue by dermrvn-code** [walkor/phpsocket.io#257]
How can I:
1. use it on a webserver?
2. use it on a local server?

I hope my question is understandable.

**Comment by walkor** [comment]
phpsocket.io needs PHP but not webserver.

Here is doc for chat example. Just use command `php start.php start -d`.
https://github.com/walkor/phpsocket.io#run-chat-example

**Comment by dermrvn-code** [comment]
But if I want to use it on a hosted webserver, is it possible?

**Comment by walkor** [comment]
Sorry, it can not &nbsp;run on&nbsp;hosted webserver.
