### ISSUE TITLE
无初始值报错

### ISSUE THREAD

**Issue by topin** [walkor/phpsocket.io#26]
发现
phpsocket.io/src/Event/Emitter.php 81行的

`php
public function emit($event_name)
`

 $event_name 没有初始值为空的话，会报错。
#0 /home/wwwroot/vendor/workerman/phpsocket.io/src/Event/Emitter.php(81): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Missing argumen...', '/home/wwwroot/p...', 81, Array)
#1 [internal function]: PHPSocketIO\Event\Emitter->emit()
#2 /home/wwwroot/vendor/workerman/phpsocket.io/src/Socket.php(306): call_user_func_array(Array, Array)
#3 /home/wwwroot/vendor/workerman/phpsocket.io/src/Socket.php(268): PHPSocketIO\Socket->onevent(Array)
#4 /home/wwwroot/vendor/workerman/phpsocket.io/src/Client.php(201): PHPSocketIO\Socket->onpacket(Array)
#5 [internal function]: PHPSocketIO\Client->ondecoded(Array)
#6 /home/wwwroot/vendor/workerman/phpsocket.io/src/Event/Emitter.php(91): call_user_func_array(Array, Array)
#7 /home/wwwroot/vendor/workerman/phpsocket.io/src/Parser/Decoder.php(34): PHPSocketIO\Event\Emitter->emit('decoded', Array)
#8 /home/wwwroot/vendor/workerman/phpsocket.io/src/Client.php(181): PHPSocketIO\Parser\Decoder->add('2[\"room\\/create...')
#9 [internal function]: PHPSocketIO\Client->ondata('2[\"room\\/create...')
#10 /home/wwwroot/vendor/workerman/phpsocket.io/src/Event/Emitter.php(91): call_user_func_array(Array, Array)
#11 /home/wwwroot/vendor/workerman/phpsocket.io/src/Engine/Socket.php(183): PHPSocketIO\Event\Emitter->emit('data', '2[\"room\\/create...')
#12 [internal function]: PHPSocketIO\Engine\Socket->onPacket(Array)
#13 /home/wwwroot/vendor/workerman/phpsocket.io/src/Event/Emitter.php(91): call_user_func_array(Array, Array)
#14 /home/wwwroot/vendor/workerman/phpsocket.io/src/Engine/Transport.php(56): PHPSocketIO\Event\Emitter->emit('packet', Array)
#15 /home/wwwroot/vendor/workerman/phpsocket.io/src/Engine/Transports/Polling.php(151): PHPSocketIO\Engine\Transport->onPacket(Array)
#16 /home/wwwroot/vendor/workerman/phpsocket.io/src/Engine/Transports/Polling.php(120): PHPSocketIO\Engine\Transports\Polling->onData('254:42[\"room\\/c...')
#17 [internal function]: PHPSocketIO\Engine\Transports\Polling->dataRequestOnEnd(Object(PHPSocketIO\Engine\Protocols\Http\Request))
#18 /home/wwwroot/vendor/workerman/phpsocket.io/src/Engine/Protocols/SocketIO.php(177): call_user_func(Array, Object(PHPSocketIO\Engine\Protocols\Http\Request))
#19 /home/wwwroot/vendor/workerman/phpsocket.io/src/Engine/Protocols/SocketIO.php(89): PHPSocketIO\Engine\Protocols\SocketIO::emitEnd(Object(Workerman\Connection\TcpConnection), Object(PHPSocketIO\Engine\Protocols\Http\Request))
#20 [internal function]: PHPSocketIO\Engine\Protocols\SocketIO::onData(Object(Workerman\Connection\TcpConnection), '254:42[\"room\\/c...')
#21 /home/wwwroot/vendor/workerman/workerman/Connection/TcpConnection.php(419): call_user_func('\\PHPSocketIO\\En...', Object(Workerman\Connection\TcpConnection), '254:42[\"room\\/c...')
#22 [internal function]: Workerman\Connection\TcpConnection->baseRead(Resource id #859)
#23 /home/wwwroot/vendor/workerman/workerman/Events/Select.php(250): call_user_func_array(Array, Array)
#24 /home/wwwroot/vendor/workerman/workerman/Worker.php(1464): Workerman\Events\Select->loop()
#25 /home/wwwroot/vendor/workerman/workerman/Worker.php(898): Workerman\Worker->run()
#26 /home/wwwroot/vendor/workerman/workerman/Worker.php(864): Workerman\Worker::forkOneWorker(Object(Workerman\Worker))
#27 /home/wwwroot/vendor/workerman/workerman/Worker.php(422): Workerman\Worker::forkWorkers()
#28 /home/wwwroot/app/Console/Commands/Lives.php(1267): Workerman\Worker::runAll()
#29 [internal function]: App\Console\Commands\Lives->handle()
#30 /home/wwwroot/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array)
#31 /home/wwwroot/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#32 /home/wwwroot/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 /home/wwwroot/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 /home/wwwroot/vendor/symfony/console/Application.php(791): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#35 /home/wwwroot/vendor/symfony/console/Application.php(186): Symfony\Component\Console\Application->doRunCommand(Object(App\Console\Commands\Lives), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#36 /home/wwwroot/vendor/symfony/console/Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#37 /home/wwwroot/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#38 /home/wwwroot/artisan(46): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#39 {main}

**Comment by walkor** [comment]
这个错误可以复现么？
