### ISSUE TITLE
Socket.IO with phpsocket.io version

### ISSUE THREAD

**Issue by nik0145** [walkor/phpsocket.io#261]
I got error.
Error: It seems you are trying to reach a Socket.IO server in v2.x with a v3.x client, but they are not compatible (more information here: https://socket.io/docs/v3/migrating-from-2-x-to-3-0/)
How do I fix it in v3.x client?

**Comment by walkor** [comment]
Please use  v2.x client.

**Comment by nik0145** [comment]
okay :(
