### ISSUE TITLE
I have this issue where I switch to daemon mode and get no communications after a connection to the server is made

### ISSUE THREAD

**Issue by binemmanuel** [walkor/phpsocket.io#269]
On daemon mode connections to the server is successfully made but no communications are made though when I check the status I notice that requests are made but nothing gets to the app. 

I've got PHP 8.0.13 with 10.3.32-MariaDB-0ubuntu0.20.04.1 Ubuntu 20.0 and I'm trying to connect from a mobile built with Flutter.
<img width="1439" alt="Screenshot 2021-12-19 at 09 14 50" src="https://user-images.githubusercontent.com/53215111/146668290-a3f26f85-4e54-4898-be33-bfd07cee2ac0.png">

**Comment by walkor** [comment]
Do you mean it works fine when you switch to non daemon mode?

**Comment by binemmanuel** [comment]
It doesn't work at all on daemon mode though everything looks fine without daemon and I've been wondering if it has a thing to do with the version I'm using on the client.

**Comment by walkor** [comment]
Do not initialize the database connection before the `Worker::runAll()` runs. Please initialize the database connection in workerStart like this.
```php
$io = new SocketIO(9120);
$io->on('workerStart', function()use($io) {
    // Init your database connection here.
});
```

**Comment by binemmanuel** [comment]
Instantiating  the database connection on workerStart fixed my problem, I appreciate the help.
