### ISSUE TITLE
Connection closes when starting a new thread using pthreads

### ISSUE THREAD

**Issue by tyurderi** [walkor/phpsocket.io#27]
I'm building a chat application using your library and for longer database/api calls I decided to use multi-threading to prevent blocking all other interactions when fetching new data or similar.

For this I am using pthreads with a wrapper class to call a method threaded.
``` php
class ThreadedCall extends \Worker
{

    protected static $nextThreadId = 1;

    protected $method = null;

    protected $params = [];

    private function __construct($threadId, $method, array $params = [])
    {
        $this->threadId = $threadId;
        $this->method   = $method;
        $this->params   = $params;
    }

    public static function call($method, array $params = [])
    {
        $threadId = static::$nextThreadId++;
        $thread   = new self($threadId, $method, $params);

        if ($thread->start())
        {
            return $thread;
        }

        return null;
    }

    public function run()
    {
        if ($this->method !== null)
        {
            call_user_func_array($this->method, $this->params);
        }
    }

}
```
``` php
$socket->on('login', function() {
    ThreadedCall::call(function() {
        // do something that takes a long time
    });
});
```

So when I execute something threaded the socket gets closed immediately with the following error information, passed to the first argument in the disconnect callback `client error`.

What I am doing wrong or is the way I am following to reach a non-blocking client application with long-time-calls wrong?

**Comment by walkor** [comment]
I don't know what is the problem.

There is another way to do that.
You can turn blocking time consuming tasks to other processes of server clusters.
So your main business process will not be blocked.

Here is an example.
Send time consuming tasks(sending mail) to other processes asynchronously and get the results back to the client.

Task.php (Deal with blocking operations).
```php
use Workerman\Worker;
$task_worker = new Worker('Text://0.0.0.0:12345');
// Many processes.
$task_worker->count = 100;
$task_worker->name = 'TaskWorker';
$task_worker->onMessage = function($connection, $task_data) {
     $task_data = json_decode($task_data, true);
     // Simulate sending mail or mysql operation etc.
     sleep(1);
     // Send result.
     $connection->send('ok');
};
Worker::runAll();
```
Run task service with command ```php Task.php start```.

Then You can send tasks to other processes of server by AsyncTcpConnection in phpsocket.io like this.
```php
    // AsyncTcpConnection for sending asynchronous task to other server cluster(lvs dns etc..).
    $task_connection = new AsyncTcpConnection('Text://127.0.0.1:12345');
    // Mail task.
    $task_data = array(
        'function'  => 'send_mail',
        'args'      => array('from'=>'xxx', 'to'=>'xxx', 'contents'=>'xxx'),
    );
    $task_connection->onConnect = function($task_connection) {
        // Send task asynchronously. 
        $task_connection->send(json_encode($task_data));
    }
    // Get results asynchronously.
    $task_connection->onMessage = function($task_connection, $task_result)use($ws_connection)     {
         // $task_result is string 'ok' in this example.
         $task_connection->close();
         // Tell websocket client that task competed.
         $ws_connection->send('task complete');
    };
    // Connect asynchronously.
    $task_connection->connect();
```

**Comment by tyurderi** [comment]
This might be the right way but unfortunately I would need this TaskWorker for every connected socket itself.

This worker would check every x seconds for new message from the original chat server (which actually only accepts http requests for its API) thats why I am following this way.

Is that possible with workerman? I would still say, that the way over the threads would be the easiest way - when it would work with your library. But as I told the connection to the socket closes when I call a function in a new thread.

Hope you can help me.
