### ISSUE TITLE
Live Demo link is not working!

### ISSUE THREAD

**Issue by alnahian2003** [walkor/phpsocket.io#270]
Provided [Live Demo](https://www.workerman.net/demos/phpsocketio-chat) link on the Readme is not working properly. Whenever I hit that link, it redirects to a 404 Not Found page.
![error-image](https://user-images.githubusercontent.com/61485238/149468084-36baec70-e0a5-4792-8438-ffcda7c814f2.png)

Please consider solving this matter if possible.
Thanks

**Comment by walkor** [comment]
Try http://demos.workerman.net/phpsocketio-chat/

**Comment by alnahian2003** [comment]
> 

Excellent! It's working :D 
Thanks for the QuickFix
