### ISSUE TITLE
After v1.1.13, phpsocket.io cannot be connected when a browser use WebSocket first

### ISSUE THREAD

**Issue by troublezzb** [walkor/phpsocket.io#274]
phpsocket.io v1.1.13
socket.io-client v2.4.0 (Chrome 98.0.4758.102 64bit)
```js
io(window.g.socketUrl, {transports: ['websocket', 'polling']})
```

The following error occurred in the browser：
> WebSocket connection to 'ws://192.168.255.1:4052/socket.io/?EIO=3&transport=websocket' failed:

**My Thoughts:**
I think this judgment is not handled well.
[src/Engine/Engine.php （commit 25243e320bf6b43f11b96974d1a54241dcd07bce）](https://github.com/walkor/phpsocket.io/commit/25243e320bf6b43f11b96974d1a54241dcd07bce#diff-f40d5c015dfe471c8cbaf78c79f9d79632a35755debecde7e5e6981def398e4c)
```php
        if ($transport === 'websocket' && empty($sid)) {
            return call_user_func($fn, self::ERROR_UNKNOWN_TRANSPORT, false, $req, $res);
        }
```
**Interim Solution:**
@jichangfeng You can try:

1. use phpsocket.io v1.1.12
2. removing the 'transport' attribute.

```js
io(window.g.socketUrl)
```
3. watching the ‘connect_error’ event（[more](https://socket.io/docs/v4/client-options/#transports)）. 
```js
const socket = io("https://example.com", {
  transports: ["websocket", "polling"] // use WebSocket first, if available
});

socket.on("connect_error", () => {
  // revert to classic upgrade
  socket.io.opts.transports = ["polling", "websocket"];
});
```

**Comment by walkor** [comment]
phpsocket.io v1.1.14 removed the judgment.
Please upgrade.
Sorry for the inconvenience.

**Comment by troublezzb** [comment]
It's work. Thanks for your prompt reply.

**Comment by jichangfeng** [comment]
Solved. Thanks。
