### ISSUE TITLE
How do i broadcast message to specific user?

### ISSUE THREAD

**Issue by bjsmasth** [walkor/phpsocket.io#28]

**Comment by walkor** [comment]
You can use ```$socket->join($some_ specific_user_group)``` on server side.
Then you can broadcast message to specific user by $io->in($some_ specific_user_group)->emit(......);

**Comment by bjsmasth** [comment]
i am not taking about group message. I am talking about private messaging

**Comment by walkor** [comment]
Use ```$socket->emit(...)``` to send message to specific user.

**Comment by bjsmasth** [comment]
I think it will emit to all users connected. how to send message by username?

**Comment by walkor** [comment]
```$socket->emit(...)``` is not emit to all users ,but the only user of the $socket.

**Comment by bjsmasth** [comment]
$usernames[$username] = $socket;

$usernames[$receiver_id]->emit();
