### ISSUE TITLE
fread(): SSL: Connection reset by peer in

### ISSUE THREAD

**Issue by den1a** [walkor/phpsocket.io#293]
Hello. I get this error from the logo. Please tell me what to pay attention to.

> PHP Warning:  fread(): SSL: Connection reset by peer in /var/www/site/vendor/workerman/workerman/Connection/TcpConnection.php on line 582

Certificate files are readable

```
'ssl' => [
  'local_cert'  => '/etc/nginx/ssl/www.site.crt',
  'local_pk'    => '/etc/nginx/ssl/www.site.crt',
  'verify_peer' => false,
]
```

**Comment by walkor** [comment]
It appears that the connection was forcibly terminated by the client, which is a predictable warning and usually does not require special handling
In the workerman source code @ is used to suppress such warnings.

**Comment by den1a** [comment]
I see @ in the source code, but I still get a lot of errors in my error log

![error](https://github.com/walkor/phpsocket.io/assets/45651923/3ae70daf-bdb3-454c-8615-3259c66e03a8)

![error2](https://github.com/walkor/phpsocket.io/assets/45651923/e57baa48-528b-4370-b867-d30851a081de)

**Comment by acuna-public** [comment]
@den1a it's not "a lot of errors", it's called stack trace showed where this error occur, so error only one here: "Connection reset by peer", it's  just warning, so you can simply supress it as @walkor mentioned because it will recover automatically in case of disconnection.
