### ISSUE TITLE
php -d 之后，socket.io.js  出现400

### ISSUE THREAD

**Issue by zoujingli** [walkor/phpsocket.io#30]
php index.php start -d; 出现 400 (Bad Request)，同域名下也不能访问了
php index.php start &; 没有问题，也可以垮域
PHP环境是5.4.3

**Comment by walkor** [comment]
服务端返回400的时候，同时http包体也会返回一个字符串，贴下包体内容吧

**Comment by zoujingli** [comment]
{"code":1,"message":"Session ID unknown"}
经检查，sid会变化，-d的时候

**Comment by zoujingli** [comment]
如果仅仅是php start是没有问题的

**Comment by walkor** [comment]
看起来是服务端业务代码发生了致命错误导致的
可以看下workerman.log看看是否有业务异常

**Comment by zoujingli** [comment]
2016-07-24 00:27:07 pid:24336 WORKER EXIT UNEXPECTED
2016-07-24 00:27:07 pid:31254 worker[PHPSocketIO:24336] exit with status 2048

**Comment by zoujingli** [comment]
正常的情况
php index.php start
php index.php start &
nohup php index.php start
nohup php index.php start &

**Comment by zoujingli** [comment]
是数据库查询问题，-d之后  Query error: MySQL server has gone away - Invalid query

**Comment by walkor** [comment]
不要在主进程直接初始化数据库连接，在on(xxx, fun)回调中初始化就没问题了
