### ISSUE TITLE
$socket->emit 输出一个较大的JSON或对象时，会引起Client终断重连

### ISSUE THREAD

**Issue by zoujingli** [walkor/phpsocket.io#31]
改为这样内容是可以正常使用的
`function socket_encode($obj) {
    return base64_encode(json_encode($obj, JSON_UNESCAPED_SLASHES));
}
$socket->emit('sync user', socket_encode($rst));`
如果直接传JSON格式也会导致Socket.io.js终断重连，只能base64下

**Comment by walkor** [comment]
可能是你的php文件自身编码不是utf8导致的

**Comment by zoujingli** [comment]
确定编码都是utf-8，并且尝试传输明文JOSN字符串（含中文）也出现中断，当base64后再传输，就没有问题了

**Comment by walkor** [comment]
根据经验，这个问题是文件自身编码不是utf8导致，请再次确认。

或者运行example中的例子试下，如果例子可以，请对比下和你代码的区别。
