### ISSUE TITLE
How to add header to implement CORS 

### ISSUE THREAD

**Issue by yuchenglin** [walkor/phpsocket.io#32]
My server-side and client-side socketio app are in different domains, so I suffer cross domain access problem. How to add CORS header at the server side like below? Thanks

```
Access-Control-Allow-Origin: {$_SERVER['HTTP_ORIGIN']}
Access-Control-Allow-Methods: POST
Access-Control-Allow-Headers: X-Requested-With, Content-Type, Accept
```

**Comment by walkor** [comment]
PHPSocket.io has not cross domain problem. 
Access-Control-Allow-Origin: will be set to the right value automatically by server side.

**Comment by acrobatius** [comment]
What about connection via SSL from other domain?
1. run server.php in example.com:2021
2. connect via **https://**websocket.io-client to example.com:2021

example.com must be https to, what about ssl? Now when i run server.php at example.com it successfully start and handshakes with http, but https make it infinity loading

**Comment by walkor** [comment]
You can use nginx as a reverse proxy for wss.
Please check https://github.com/nicokaiser/nginx-websocket-proxy
