### ISSUE TITLE
Error during WebSocket handshake: Unexpected response code: 400

### ISSUE THREAD

**Issue by tyurderi** [walkor/phpsocket.io#33]
This error appears when trying to reconnect after I used `pcntl_fork()` inside a socket listener callback.

``` php
$app = new SocketIO(8303);
$app->on('connection', function($socket) {
    $socket->('action', function() use ($socket) {
        if (pcntl_fork())
        {
            sleep(2); // do something that takes some secs
            $socket->emit('action success');
        }
    });
});
```

Any other workaround or fix instead of using an AsyncTcpConnectio mentioned here? https://github.com/walkor/phpsocket.io/issues/27#issuecomment-232035919

**Comment by walkor** [comment]
pcntl_fork will create process again and again when client connecting server in your case. Every process has  separate variable environment and can not work as your expected.

**Comment by tyurderi** [comment]
You're wrong - `pcntl_fork` will create a new process again and again when the socket received a package named `action` in my case - but that doesn't care in this test case.

I can't reconnect after minutes since the process (started with `pcntl_fork`) is already closed/finished.

Are you sure its the different variable environment?

**Comment by walkor** [comment]
Yes.
Client and server will communicate several times to complete the handshake of socket.io.
When client create a new websocket connection to server, the client may be connect to a wrong process that with out required variables which is setted by last request to another process.

**Comment by tyurderi** [comment]
Well, do you know a workaround/fix for this?

**Comment by walkor** [comment]
Try the codes below, I can't guarantee that it will work very well.
```php
$app = new SocketIO(8303);
$app->on('connection', function($socket) {
    $socket->('action', function() use ($socket) {
        if (0 === pcntl_fork())
        {
            sleep(2); // do something that takes some secs
            $socket->emit('action success');
            // close child process
            Worker::stopAll();
        }
    });
});
```
