### ISSUE TITLE
Access PHP session.

### ISSUE THREAD

**Issue by utan** [walkor/phpsocket.io#37]
Hi, i am watching this repo and would like to use it.  But I have a question, can we access php session? 

If so any snippe how to accomplish it?

**Comment by walkor** [comment]
PHPSocket.IO not support session.

**Comment by utan** [comment]
Do you know a way to do this without using Node php-unserialize? 

If I understand well then your program is to be used instead of Node in Server Side right?

Can we access php session if we have the session id? and pull it from your server side php?

I used to Node and socket.io but this implementation doesn't click on me yet..!

**Comment by walkor** [comment]
> If I understand well then your program is to be used instead of Node in Server Side right?

Yes.

> Can we access php session if we have the session id? and pull it from your server side php?

Yes.

If you can get session id , more recent, you get the raw session data then you can use ```session_decode``` to get the session content. Codes like this.

```php
session_id = 'vj0ps3tec5t539pg31g8hnvmq0';
$session_path = session_save_path();
if (!$session_path) {
     $session_path = sys_get_temp_dir();
}
$session_file_path = $session_path . '/sess_' . $session_id;
@session_start(); // Session_start is necessary, otherwise session_decode will fail.
session_decode(file_get_contents($session_file_path));
var_dump($_SESSION);
```

**Comment by utan** [comment]
I guess we should pull it from your phpsocket.io can we?

clients connects to php server based in your program then we inspect the cookie and based on that we pull the php session?
I don't know if that is the process, I am unsure if your program doesn't interact with the client side...

I guess I don't have a clear view of what your program does..

**Comment by walkor** [comment]
> I guess we should pull it from your phpsocket.io can we?

Yes.

> clients connects to php server based in your program then we inspect the cookie and based on that we pull the php session?

Yes.

**Comment by utan** [comment]
Oh outstanding so kool will try it out..

**Comment by utan** [comment]
No, npm I have manage to install Composer, and require phpSocket.io , worked fine on ubuntu server 14.04 ..

 Thanks man
