### ISSUE TITLE
How to Broadcast notification to every user?

### ISSUE THREAD

**Issue by engrKaka** [walkor/phpsocket.io#38]
How can I use your repo to broadcast any notification to all users without user interaction i.e. currently there must be some client side activity (as of my knowledge) to notify other users, but i want to notify users from server, actually it will be a count down timer based on server time.

**Comment by walkor** [comment]
Issue #23 may help.

**Comment by engrKaka** [comment]
Thanks walkor for your reference. 
i got this error when tried to start emit.php
`PHP Warning:  stream_socket_client(): unable to connect to tcp://127.0.0.1:2206 (Connection refused) in /var/www/html/package/socket.php/src/Emitter.php on line 25
PHP Fatal error:  Uncaught Exception: Connection refused in /var/www/html/package/socket.php/src/Emitter.php:28
Stack trace:
#0 /var/www/html/package/socket.php/src/Emitter.php(20): Emitter->connect()
#1 /var/www/html/package/socket.php/test/emit.php(5): Emitter->__construct()
#2 {main}
  thrown in /var/www/html/package/socket.php/src/Emitter.php on line 28`
Can you pleas guide me with this?
I want to integrate it with "phpsocket.io" so that both "server.php" and "emit.php" can emit to same visitors
