### ISSUE TITLE
call to member packet() on non object

### ISSUE THREAD

**Issue by utan** [walkor/phpsocket.io#40]
Hi,

 `
PHP Notice:  Trying to get property of non-object in /php_socket.io/vendor/workerman/phpsocket.io/src/Socket.php on line 189

Notice: Trying to get property of non-object in /php_socket.io/vendor/workerman/phpsocket.io/src/Socket.php on line 189
PHP Fatal error:  Call to a member function packet() on a non-object in /php_socket.io/vendor/workerman/phpsocket.io/src/Socket.php on line 192

Fatal error: Call to a member function packet() on a non-object in /php_socket.io/vendor/workerman/phpsocket.io/src/Socket.php on line 192
WORKER EXIT UNEXPECTED E_ERROR Call to a member function packet() on a non-object in /php_socket.io/vendor/workerman/phpsocket.io/src/Socket.php on line 192
`

I got this error : how to duplicate

server side..
```
<?php
// when the client emits 'new message', this listens and executes
    $socket->on('new message', function ($data)use($socket){
        // we tell the client to execute 'new message'
        $socket->broadcast->emit('new message', array(
            'username'=> $socket->username,
            'message'=> $data
        ));
    });
?>

```

and client side : 

```
setInterval(function(){
    socket.emit('new message', { msg :'sending this from chrome.'});
  },1000);

```

Now just reload the browser f5 as many times, my guess is that when the browser is sending the payload the socket is disconnected and crashes the server...

thanks.

**Comment by utan** [comment]
```
/**
 * Disconnects from all namespaces and closes transport.
 *
 * @api private
 */

    public function disconnect()
    {
        foreach($this->sockets as $socket)
        {
            $socket->disconnect();
        }
        $this->sockets = array();
        $this->close();
    }
```
is $socket->disconnect(); intended without @param in Client.php line 93?

I got a warning notice about needing the parameter..

```

**Comment by walkor** [comment]
I will try to find the problem. thanks.

**Comment by limingxinleo** [comment]
这里还是报错啊
