### ISSUE TITLE
Fatal error: Call on removeAllListeners() on a non-object

### ISSUE THREAD

**Issue by utan** [walkor/phpsocket.io#44]
I have the following error:

```


Fatal error: Call to a member function removeAllListeners() on a non-object in /opt/serverSideNode/php_socket.io/vendor/workerman/phpsocket.io/src/Client.php on line 252
WORKER EXIT UNEXPECTED E_ERROR Call to a member function removeAllListeners() on a non-object in /opt/serverSideNode/php_socket.io/vendor/workerman/phpsocket.io/src/Client.php on line 252
worker[PHPSocketIO:2024] exit with status 65280

```

What is the correct usage of $socket->disconnect(); does the argument needs to be given and what is the correct argument?

Please a correct usage must be given, using true as argument give me the above error..

**Comment by utan** [comment]
No idea? I am having problems disconnecting users that have same session.. or if want to have some ban tool..

**Comment by walkor** [comment]
fixed
