### ISSUE TITLE
HHVM 

### ISSUE THREAD

**Issue by nirgendswo** [walkor/phpsocket.io#46]
Hello, 

i have tried to run a server with HHVM (5.6.99-hhvm, 3.11.1), but i get this error,

> Fatal error: Call to undefined function Workerman\Connection\stream_set_read_buffer() in /var/www/share/app/vendor/workerman/workerman/Connection/TcpConnection.php on line 214
> WORKER EXIT UNEXPECTED 
> worker[PHPSocketIO:4942] exit with status 65280

This error shows only if a client connects to a server.

But Workermen supported HHVM, or?

**Comment by walkor** [comment]
Fixed, Please update.
