### ISSUE TITLE
这个如果搞分布式的话是不是与workerman-chat的原理如出一辙？

### ISSUE THREAD

**Issue by playwolf719** [walkor/phpsocket.io#48]
另外，还有个问题，sockJs在低级浏览器（不支持的websocket），是自己再造一个websocket协议，还是用了新的自定义的协议？

**Comment by walkor** [comment]
可以网上搜下socket.io分布式方案。
不支持websocket的浏览器会自动退化成comet

**Comment by playwolf719** [comment]
@walkor 谢啦
