### ISSUE TITLE
Not Working.

### ISSUE THREAD

**Issue by RayHughes** [walkor/phpsocket.io#49]
Cannot get this to talk together. Using SSL. Using simple chat method and simple chat from socket io.

**Comment by walkor** [comment]
Using nginx as ssl proxy.
https://www.nginx.com/resources/admin-guide/nginx-tcp-ssl-termination/

**Comment by RayHughes** [comment]
Okay i got it to work over http just not https. Will try ssl proxy

**Comment by RayHughes** [comment]
So I'm currently using NGINX configured to redirect all traffic to SSL. When I try to create the web socket connection over port 8443 it connects but requests fall to go through. Not sure how to proxy this if I'm already configured?

**Comment by walkor** [comment]
https://www.nginx.com/resources/admin-guide/nginx-tcp-ssl-termination/
This link may help you.

Complete Example
```
stream {
    upstream stream_backend {
         server backend1.example.com:12345;
         server backend2.example.com:12345;
         server backend3.example.com:12345;
    }
 
    server {
        listen                12345 ssl;
        proxy_pass            stream_backend;
 
        ssl_certificate       /etc/ssl/certs/server.crt;
        ssl_certificate_key   /etc/ssl/certs/server.key;
        ssl_protocols         SSLv3 TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers           HIGH:!aNULL:!MD5;
        ssl_session_cache     shared:SSL:20m;
        ssl_session_timeout   4h;
        ssl_handshake_timeout 30s;
     }
}
```
