### ISSUE TITLE
Emit on a set interval

### ISSUE THREAD

**Issue by RayHughes** [walkor/phpsocket.io#51]
Hello,

Awesome framework, it is doing an amazing job powering one of my websites chatrooms. I did have a question however as I have not been able to solve this problem yet.

Basically, I would like to send a message to my chatroom every x minutes. I have figured out how this can be completed yet. I tried your example provided for workman, but have not been able to use both together.

Any feedback is appreciated,
Ray

**Comment by walkor** [comment]
Here is a timer example for phpsocket.io.
```php
use Workerman\Lib\Timer;
$io = new SocketIO(2020);
// Emit workerStart when process starting...
$io->on('workerStart', function()use($io){
    $time_interval = 10;
    Timer::add($time_interval, function()use($io){
        $io->emit('new message', array(
            'username'=> 'admin',
            'message'=> 'blabla...'
        ));
    });
});

$io->on('connection', function($socket){
 ...
```

**Comment by adrianofoschi** [comment]
can I use the Timer into "on connection" and destroy It "on disconnect"?

**Comment by walkor** [comment]
Yes you can.

**Comment by willowTank** [comment]
Hi thanks for your reply walkor. I am developing game like https://www.bustabit.com/ .
This is game logic code part.
`    while (FALSE) {
        $game_engine->game_starting($io);
        sleep(5);
        $game_engine->player_bet($io);
        $game_engine->game_started($io);
        $start_time = $util->getCurrentMilliTime();
        $lastTickTime = $start_time;
        while (true) {
            if ($util->getCurrentMilliTime() - $lastTickTime < GameEngine::$TICK_INTERVAL_TIME) {
                sleep(0.01);
                continue;
            }
            $currentTime = $util->getCurrentMilliTime();
            $elapsed = $currentTime - $start_time;
            $val = floor(100*pow(M_E, 0.00006*$elapsed));
            $lastTickTime = $currentTime;
            $game_engine->game_tick($io, $elapsed);
            if ($val >= 3.4)
            {
                break;
            }
        }
        $game_engine->game_crash($io, $elapsed, 3.4);
        sleep(1);
    }`

but I don't know how I can implement it using this.
Please help me.
