### ISSUE TITLE
Multiple servers for Development/Production setup

### ISSUE THREAD

**Issue by ptdev** [walkor/phpsocket.io#55]
Hi, I have a webapp that uses this socketio implementation for a chat/notification box.

Recently, I needed to split my app into DEV and PROD versions so I added a check on my server.php to detect the folder name and change ports accordingly.

Something like this:

```
// detect environment
$mode = (strpos(dirname(__DIR__), '-dev') !== false) ? 'dev' : 'prod';

if($mode === 'dev') {
    $channel = new Channel\Server('0.0.0.0', 3206);
    $io = new SocketIO(3020);
} elseif($mode === 'prod') {
    $channel = new Channel\Server('0.0.0.0', 2206);
    $io = new SocketIO(2020);
}
```

So, if I run "server.php start" inside a folder that has "-dev" in the name, it starts the servers on ports 3020/3206, otherwise it will start on ports 2020/2206.

This is working fine, but the servers seem to be communicating with each other, because when I type something on the DEV's chat message, the message appears on the PROD and vice-versa.

I've used Chrome developer tools to check the connections and each version seems to be correctly connected to the different versions, so:

PROD app at "myapp.example.com" is connected to wss://myapp.example.com/socket.io/...
DEV app at "myapp-dev.example.com" is connected to wss://myapp-dev.example.com/socket.io/...

In case it helps here are the status message for both when there's one user connected to each version:

DEV:

```
Workerman[server.php] status
---------------------------------------GLOBAL STATUS--------------------------------------------
Workerman version:3.3.4          PHP version:5.6.27-0+deb8u1
start time:2016-12-02 20:10:37   run 0 days 0 hours
load average: 0.05, 0.05, 0.05   event-loop:select
2 workers       2 processes
worker_name   exit_status     exit_count
ChannelServer 0                0
PHPSocketIO   0                0
---------------------------------------PROCESS STATUS-------------------------------------------
pid	memory  listening               worker_name   connections total_request send_fail throw_exception
3301	1.75M   frame://0.0.0.0:3206    ChannelServer 0           0              0         0
3302	2.75M   socketIO://0.0.0.0:3020 PHPSocketIO   3           255            0         0
```

PROD:

```
Workerman[server.php] status
---------------------------------------GLOBAL STATUS--------------------------------------------
Workerman version:3.3.4          PHP version:5.6.27-0+deb8u1
start time:2016-12-02 20:10:32   run 0 days 0 hours
load average: 0.12, 0.07, 0.05   event-loop:select
2 workers       2 processes
worker_name   exit_status     exit_count
ChannelServer 0                0
PHPSocketIO   0                0
---------------------------------------PROCESS STATUS-------------------------------------------
pid	memory  listening               worker_name   connections total_request send_fail throw_exception
3295	1.75M   frame://0.0.0.0:2206    ChannelServer 2           273            0         0
3296	2.75M   socketIO://0.0.0.0:2020 PHPSocketIO   3           292            0         0
```

So, my question is, how can I run two completely separate versions so I can properly separate my development tests from the production version?

Thank you.

**Comment by ptdev** [comment]
After some more investigation it appears that this code (that is just after what was posted above):

```
$io->on('workerStart', function() use($io) {
    $io->adapter('\PHPSocketIO\ChannelAdapter');
});
```

Is what seems to be connecting both versions to the same socket. I see that ChannelAdapter has a hardcoded port  to 2206. Is there any way to define the port on the code above when defining the adapter?

**Comment by walkor** [comment]
\PHPSocketIO\ChannelAdapter will use 2206 as default port.
You can change it like this.

```php
// detect environment
$mode = (strpos(dirname(__DIR__), '-dev') !== false) ? 'dev' : 'prod';

if($mode === 'dev') {
    $channel = new Channel\Server('0.0.0.0', 3206);
    $io = new SocketIO(3020);
    // ========ChannelAdapter========
    $io->on('workerStart', function()use($io){
        ChannelAdapter::$port = 3206;
        $io->adapter('\PHPSocketIO\ChannelAdapter');
    });
} elseif($mode === 'prod') {
    $channel = new Channel\Server('0.0.0.0', 2206);
    $io = new SocketIO(2020);
    // ========ChannelAdapter========
    $io->on('workerStart', function()use($io){
        ChannelAdapter::$port = 2206;
        $io->adapter('\PHPSocketIO\ChannelAdapter');
    });
}
```

Good luck.

**Comment by ptdev** [comment]
Thanks a lot man, that's exactly what I needed, I just couldn't figure out this part:

`ChannelAdapter::$port = 3206;`

It's working perfectly now, thanks again, and great work on your github repos!
