### ISSUE TITLE
如何让server.php接收get参数

### ISSUE THREAD

**Issue by lly835** [walkor/phpsocket.io#6]
我想让server.php接收get参数，然后传给客户端，不知道如何操作。下面这种方式是不行的

```<?php
use Workerman\Worker;
use PHPSocketIO\SocketIO;

// composer autoload
include __DIR__ . '/vendor/autoload.php';

$io = new SocketIO(2021);

// 当有客户端连接时
$io->on('connection', function($connection)use($io){
    // 定义chat message事件回调函数
//    $connection->on('chat message', function($msg)use($io){
        // 触发所有客户端定义的chat message from server事件
        $io->emit('chat message', $_GET['key']);
//    });
});

Worker::runAll();
```

![image](https://cloud.githubusercontent.com/assets/2225913/13034980/a12cb4bc-d37e-11e5-83bb-bf2f077a7cc8.png)

**Comment by walkor** [comment]
server.php文件不是用浏览器访问的。是在命令行里面运行的。
```php server.php start``` debug方式运行 或者 ```php server.php start -d```守护进程方式运行

客户端给服务端发送数时据客户端直接emit即可，不用get传递。

phpsocket.io使用方法参考docs目录的手册 https://github.com/walkor/phpsocket.io/tree/master/docs/zh

**Comment by W12S12E12** [comment]
https://github.com/Robinlim/Tangram2/commit/3311644e7a46757dad2bb3b77efb5df9958329ed

**Comment by lly835** [comment]
我想说，其实是有这种需求的。。。

**Comment by walkor** [comment]
PHPSocket.IO里面可以这样获得get参数
```
$io->on('connection', function($socket)use($io){
        $io->emit('chat message', $socket->request->_query['key']);
});
```

**Comment by lly835** [comment]
还是不行
![image](https://cloud.githubusercontent.com/assets/2225913/13604079/0b29fab4-e57c-11e5-9609-fcc4b313cfa0.png)

我希望访问浏览器，将key的值推送给客户端

**Comment by walkor** [comment]
上面说过了，server.php 不是用浏览器来访问的，是命令行运行的

**Comment by lly835** [comment]
那就是说，不能实现我说的那种需求？

**Comment by walkor** [comment]
获取get参数能实现，上面已经给了方法。

**Comment by lly835** [comment]
我想在server.php里获取  又想通过浏览器访问server.php

**Comment by walkor** [comment]
你不了解phpsocket.io的运行机制，我是没办法和你沟通的。
你就当phpsocket.io无法满足你的需求吧。
