### ISSUE TITLE
How can i send a message to all user in php script.

### ISSUE THREAD

**Issue by xmannv** [walkor/phpsocket.io#60]
Hi workerman,

How can i send a message to phpsocket server from some of my php script. And that message will be broatcast to all user. Sorry i don't know how to do it from outside phpsocket script.

**Comment by walkor** [comment]
See https://github.com/walkor/phpsocket.io/issues/23 .

**Comment by xmannv** [comment]
Thanks man

i got it worked now !

**Comment by devyaz** [comment]
@xmannv , how didi u do it, can u plis share your code?

**Comment by xmannv** [comment]
follow this post @devyaz  https://github.com/walkor/phpsocket.io/issues/23

**Comment by H4mdan90** [comment]
@xmannv would you like to share your code, please? i have follow the post #23 but still can not work
