### ISSUE TITLE
How to create a room 

### ISSUE THREAD

**Issue by tolew1** [walkor/phpsocket.io#63]
This might sound like a easy question, but I'm trying to understand this. I need to be able to create rooms/channels for each user. I'm not understanding the syntax because I don't see any examples of creating and joining rooms.

**Comment by walkor** [comment]
You can call join to subscribe the socket to a given channel:
```php
$io->on('connection', function($socket){
  $socket->join('some room');
});
```
And then simply use to or in (they are the same) when broadcasting or emitting:
```php
$io->to('some room')->emit('some event');
```
To leave a channel you call leave in the same fashion as join.
