### ISSUE TITLE
event callback

### ISSUE THREAD

**Issue by adrianofoschi** [walkor/phpsocket.io#64]
Hello, I am trying to reimplement [Signalmaster](https://github.com/andyet/signalmaster) using PHP.

The first issue that I have is with on join event.

```
function join(name, cb) {
            safeCb(cb)(null, describeRoom(name));
            client.join(name);
            client.room = name;
        }

function safeCb(cb) {
    if (typeof cb === 'function') {
        return cb;
    } else {
        return function () {};
    }
}

function describeRoom(name) {
        var adapter = io.nsps['/'].adapter;
        var clients = adapter.rooms[name] || {};
        var result = {
            clients: {}
        };
        Object.keys(clients).forEach(function (id) {
            result.clients[id] = adapter.nsp.connected[id].resources;
        });
        return result;
    }
```

The problem is with the "cb" callback. I don't understand What is it. With Chrome I see It serves this response:
430[null, {client: {}}]

How can I obtain It with phpsocketio? I see it's something regarding ACK bit I don't really know What is it.

**Comment by adrianofoschi** [comment]
I found two problems in that code in my use case:

```
public function onevent($packet)
    {
        $args = isset($packet['data']) ? $packet['data'] : array();

        if (!empty($packet['id']))
        {
            $args[] = $this->ack($packet['id']);
        }
        call_user_func_array(array($this, 'parent::emit'), $args);
    }
```

replacing that line `if (!empty($packet['id']))` 
with `if (!empty($packet['id']) || $packet['id'] === 0)` 
becouse my first packet has id 0 and does not pass the if.

The latest problem is with `hasBin` function that is not defined
```
public function ack($id)
    {
        $self = $this;
        $sent = false;
        return function()use(&$sent, $id, $self){
            // prevent double callbacks
            if ($sent) return;
            $args = func_get_args();
            $type = hasBin($args) ? Parser::BINARY_ACK : Parser::ACK;
            $self->packet(array(
                'id' => $id,
                'type' => $type,
                'data' => $args
            ));
        };
    }
```

**Comment by walkor** [comment]
Thanks for your issue.
About Signalmaster , I do not know what's the "cb" callback too : ( . 
I just reimplement socket.io using php and named phpsocket.io, but I do not know all the details of socket.io and some features are not implemented with Phpsocket.io including namespace. I'm not sure if that can be obtained using phpsocketio.

About two problems in that code I  think you are right.
Can you send a pull request?

**Comment by adrianofoschi** [comment]
The cb should be the "acknowledgment callback", I don't know what's exactly too, but It works now :D
I'm finishing to test it, I will do pull request soon.
Thanks you

**Comment by adrianofoschi** [comment]
It was solved with my pull request https://github.com/walkor/phpsocket.io/pull/71
