### ISSUE TITLE
How to use this for group chat with android mobile platform

### ISSUE THREAD

**Issue by Punith1234** [walkor/phpsocket.io#66]
Hey first thanks alot for your work, I wanted to know how to implement this group chat dynamically with android or mobile platform.. , Let's say i want to create a group chat among the gorup of people who are in a team, Team can be many also user can create new teams, In this case how this gonna help me out, Also how to connect to socket

**Comment by walkor** [comment]
Use ```socket->join($group)``` to join a group. And use ```$io->in($group)->emit(...);``` to emit message to users in the group. In socket.io you do not need to pre-create groups, just use ```join``` method. 

Here is a example to show how to use ```socket->join``` and ```io->in``` method.
Server side.
```php
<?php
require_once __DIR__ . '/vendor/autoload.php';
use PHPSocketIO\SocketIO;
use Workerman\Worker;

$io = new SocketIO(3120);
$io->on('connection', function($socket)use($io){
  $socket->on('join group', function($group)use($socket){
    $socket->join($group);
  });
  $socket->on('chat message', function($data)use($io){
    $group = $data['group'];
    $msg   = $data['msg'];
    $io->in($group)->emit('chat message', $msg);
  });
});
Worker::runAll();
```
Client side(javascript).
```javascript
var socket = io('http://127.0.0.1:3120');
socket.on('connect', function(){
    socket.emit('join group', 'group_id_xx');
    socket.on('chat message', function(msg){
        console.log(msg);
    });
    socket.emit('chat message', {group:"group_id_xx", msg:"hello"});
});
```
<br>
<br>

**Some Clients for socket.io in mobile platform.**

Socket.io clients for android.
https://github.com/socketio/socket.io-client-java
https://github.com/koush/AndroidAsync

Socket.io clients  for IOS.
https://github.com/socketio/socket.io-client-swift
https://github.com/MegaBits/SIOSocket

**Comment by Punith1234** [comment]
Hey, 
thanks alot for the response.

Also i wanted to know how to use the group name dynamically, Lets say user create a new team for chat which as ID specific., Now i want to connect that team as group chat, also note user can create many team as he wants.

**Comment by walkor** [comment]
> Lets say user create a new team for chat which as ID specific.

Yes, use ```$socket->join(ID)``` to join the team group.

**Comment by Punith1234** [comment]
Hey that's great, 

Now we know how to join a user to a particular group or team chat. How to retrieve current group which user is joined..? cause we want to know how to emit back to same ID using group ID

**Comment by Punith1234** [comment]
Hi Walkor,

$io = new SocketIO(3120);
$io->on('connection', function($socket)use($io){
  $socket->on('join group', function($group)use($socket){
    $socket->join($group);
  });
  $socket->on('chat message', function($data)use($io){
    $group = $data['group'];
    $msg   = $data['msg'];
    $io->in($group)->emit('chat message', $msg);
  });
});

In this function ... Why it is inside $io->on('connection', function($socket)use($io) can't we use $socket->on('chat message', function($data)use($io) directly.. does client should emit "connection" first

**Comment by Punith1234** [comment]
got it
