### ISSUE TITLE
TCP error - connection not established

### ISSUE THREAD

**Issue by Punith1234** [walkor/phpsocket.io#67]
i"ve added 

se Workerman\Worker;
use PHPSocketIO\SocketIO;

require_once __DIR__ . '/../../vendor/autoload.php';

// listen port 3120 for socket.io client

$io = new SocketIO(3120);
$io->on('connection', function($socket)use($io){
    $socket->on('join group', function($group)use($socket){
        $socket->join($group);
    });
    $socket->on('chat message', function($data)use($io){
        $group = $data['group'];
        $msg   = $data['msg'];
        $io->in($group)->emit('chat message', $msg);
    });
});
Worker::runAll();

and 

Client side

var socket = io('https://my ip address:3120');
            socket.on('connect', function(){

                socket.emit('join group', 'group_id_xx');
                socket.on('chat message', function(msg){
                    console.log(msg);
                });
                socket.emit('chat message', {group:"group_id_xx", msg:"hello"});
            });

![screen shot 2017-01-26 at 12 00 08 pm](https://cloud.githubusercontent.com/assets/13044958/22322030/27c5e65a-e3bf-11e6-81a3-06443a08d3e8.png)

Please help me

**Comment by gunjotSinghMansa** [comment]
How did you make it work? Can you please help!

**Comment by Punith1234** [comment]
@gunjotSinghMansa  you need to allow port -- i.e, 3120 in my case .. in AWS if your are using an AWS instance..
