### ISSUE TITLE
降级到polling的时候无法处理中文和其他UTF8字符

### ISSUE THREAD

**Issue by ayaka209** [walkor/phpsocket.io#73]
服务端使用Simple chat示例
客户端使用socket.io(-client) 1.72

无法触发服务端的on事件，命令行debug模式无任何报错

另外求wss原生支持啊_(:зゝ∠)_

**Comment by walkor** [comment]
如果是urf-8字符处理不了，应该是网页编码不是utf-8或者网页源文件本身不是utf-8编码导致的.
可以直接测试 [examples/chat](https://github.com/walkor/phpsocket.io/tree/master/examples/chat) 试下。

下面是支持ssl(wss)的方法，刚刚加的特性，需要更新下workerman和phpsocket.io。
```php
use Workerman\Worker;
use PHPSocketIO\SocketIO;

$context = array(
    'ssl' => array(
        'local_cert' => '/etc/ssl/your.pem',
        'local_pk'   => '/etc/ssl/your.key',
    )
);
$io = new SocketIO(2021, $context);
$io->on('connection', function($socket)use($io){
  $socket->on('chat message', function($msg)use($io){
    $io->emit('chat message', $msg);
  });
});

Worker::runAll();
```

**Comment by ayaka209** [comment]
感谢回复。
网页确认是UTF8，同样的网页用nodejs的server处理正常。
稍后有空会测试一下example/chat

**Comment by ayaka209** [comment]
经过测试，
example/chat也不行。

需要特别强调的是，只有降级polling的时候才会遇到这个问题，websocket并没有问题。

**Comment by walkor** [comment]
已经修复。
但是会显示乱码，乱码的原因是socket.io官方的客户端[socket.io-client](https://github.com/socketio/socket.io-client)使用了https://github.com/mathiasbynens/utf8.js编码了utf8字符导致，socket.io官方的socket.io-client为何要将其编码原因目前还不清楚。
以下是socket.io官方nodes版本的界面结果，同样是乱码。
![image](https://cloud.githubusercontent.com/assets/6073368/22697368/3148c84c-ed8c-11e6-964a-cfc9c39927a4.png)

**Comment by ayaka209** [comment]
感谢！
