### ISSUE TITLE
sockets authentication

### ISSUE THREAD

**Issue by INHack20** [walkor/phpsocket.io#75]
Hello, does liberia support sockets authentication?

An example with nodejs and socket.io at https://github.com/auth0/socketio-jwt

**Comment by walkor** [comment]
Just emit authentication message to server.

```js
var socket = io('http://ip:port');
socket.on('connect', function(){
    socket.emit('login', secret_key);
});
```

```php
$io->on('connection', function($socket){
    $socket->on('login', function ($secret_key)use($socket){
        if (!your_auth_check_func($sectet_key)) {
            return $socket->disconnect();
        }
    });
}
```

**Comment by INHack20** [comment]
Thanks, I already have an idea how to do it.

I will test the library, first time I use socket.io in pure php, I have always used it with nodejs.

I will test the performance and stability, any suggestions I can make it.

Thanks for sharing.

**Comment by walkor** [comment]
You are welcome.
