### ISSUE TITLE
About distributed deployment.

### ISSUE THREAD

**Issue by sunsonliu** [walkor/phpsocket.io#77]
How to deploy distributed.

**Comment by walkor** [comment]
PHPSocket.io already support multiple servers by Channel Adapter .

For example you have 3 servers server_A server_B server_C.
Server_A is a channel server and start script like this.
```php
use Workerman\Worker;
require_once __DIR__ . '/vendor/autoload.php';

// =======ChannelAdapter server========
$channel = new Channel\Server('0.0.0.0', 3206);
Worker::runAll();
```
Server_B and Server_C is phpsocket.io server and codes like this.
```php
use Workerman\Worker;
use PHPSocketIO\SocketIO;
require_once __DIR__ . '/vendor/autoload.php';

$io = new SocketIO(2020);
$io->on('workerStart', function()use($io){
    ChannelAdapter::$ip = 'ip_of_server_A';
    ChannelAdapter::$port = 3206;
    $io->adapter('\PHPSocketIO\ChannelAdapter');
});
$io->on('connection', function($socket)use($io){
    $socket->on('chat message', function($msg)use($io){
        $io->emit('chat message', $msg);
  });
});
Worker::runAll();
```

**Comment by sunsonliu** [comment]
sorry, I can not find Channel/Server.php . where can I get Channel/Server.php?

**Comment by walkor** [comment]
https://github.com/walkor/Channel

**Comment by sunsonliu** [comment]
thks!

**Comment by sunsonliu** [comment]
After I use Channel to implement distributed deployment, I find "$io->to('room_num')->emit()" can not work properly. Does Channel support room?

**Comment by sunsonliu** [comment]
![image](https://cloud.githubusercontent.com/assets/998441/23906856/3f8c3094-090a-11e7-8c29-408c2569a8af.png)
This is wrong! Should be write as below:
![image](https://cloud.githubusercontent.com/assets/998441/23906879/57bf6654-090a-11e7-88a8-1f0c293eb4d2.png)

**Comment by walkor** [comment]
Yes, you are right.
