### ISSUE TITLE
Is the room support implemented? By example

### ISSUE THREAD

**Issue by INHack20** [walkor/phpsocket.io#78]
io = socketio.listen(server);

// handle incoming connections from clients
io.sockets.on('connection', function(socket) {
    // once a client has connected, we expect to get a ping from them saying what room they want to join
    socket.on('room', function(room) {
        socket.join(room);
    });
});

// now, it's easy to send a message to just the clients in a given room
room = "abc123";
io.sockets.in(room).emit('message', 'what is going on, party people?');

// this message will NOT go to the client defined above
io.sockets.in('foobar').emit('message', 'anyone in this room yet?');

Gracias! (Thanks)

**Comment by walkor** [comment]
Yes, that codes in phpsocket.io like this.
```php
use Workerman\Worker;
use PHPSocketIO\SocketIO;

// listen port 2021 for socket.io client
$io = new SocketIO(2021);
$io->on('connection', function($socket) use ($io){
  $socket->on('room', function($room){
    $socket->join($room);
  });
  $socket->on('broadcast something', function($message)use($io){
     $io->sockets->in('room')->emit('message', 'anyone in this room yet?');
  })
});
Worker::runAll();
```

**Comment by INHack20** [comment]
Thank you very much! It works to perfection!
