### ISSUE TITLE
pcntl_signal()  Call to undeclared Funtion

### ISSUE THREAD

**Issue by devyaz** [walkor/phpsocket.io#81]
Hi Walkor
am getting this error when i want to start server
`$ php start.php start

Fatal error: Call to undefined function Workerman\Lib\pcntl_signal() in C:\Users
\Martin Mtawali\Desktop\phpsocket.io-master\vendor\workerman\workerman\Lib\Timer
.php on line 57
`

**Comment by walkor** [comment]
phpsocket.io if only for linux.
Windows please use https://github.com/walkor/phpsocket.io-for-win.

**Comment by devyaz** [comment]
thank you walkor, i was testing on my pc before i can put on my unix server, i guess it will work on Unix No?

**Comment by walkor** [comment]
Yes.
