### ISSUE TITLE
Sending events from Php Script to a specific user connection

### ISSUE THREAD

**Issue by gunjotSinghMansa** [walkor/phpsocket.io#83]
I checked this issue  #23 (Sending events from php) , and it lets us broadcast message to all users using Emitter class from phpsocket.io-emitter 

But i don't want to broadcast message to all users, but to a specific user. How to achieve this? Can you please help!

**Comment by gunjotSinghMansa** [comment]
Also, If there is any way to send message from PHP script to PHPSocketIO server?

**Comment by devyaz** [comment]
this is how i do it to send message or any event to a specific user
` // when the client emits 'new message', this listens and executes
    $socket->on('message', function ($message,$indx,$user)use($socket){
     global $names, $ids,$id;  //$names is the array that keeps all connected users, $ids is connected user socket id// 
       $id=array_search($indx, $ids); //look for socket id of $user
        var_dump($id);
        $name=$names[$id];//we use the $id we found above to locate the the guy sending msg
        var_dump($name);
        $socket->broadcast->to($indx)->emit('message',$user, $message,$name);//$indx being the receipient

    });
`
u could use Mysql to store name's and socket id's here am using in memory(Server RAM)
to store users and their socket id's below the full socket server
`
<?php
use Workerman\Worker;
use Workerman\WebServer;
use Workerman\Autoloader;
use PHPSocketIO\SocketIO;

// composer autoload
require_once __DIR__ . '/../vendor/autoload.php';

$io = new SocketIO(2020);
$names=[];$ids=[]; $id; //declaring the arrays to store names and socket id's and anvariable id.
$io->on('connection', function($socket){
    $socket->addedUser = false;
    // when the client emits 'new message', this listens and executes
    $socket->on('message', function ($message,$indx,$user)use($socket){
     global $names, $ids,$id;
       $id=array_search($indx, $ids);
        var_dump($id);
        $name=$names[$id];
        var_dump($name);
        **$socket->broadcast->to($indx)->emit('message',$user, $message,$name);**

    });

    // when the client emits 'new_client', this listens and executes
    $socket->on('new_client', function ($username,$cb) use($socket){
        global $names, $ids,$id,$io ;
        if(in_array($username,$names)){
          $cb(false);
        }else{
        $cb(true);
        // we store the username in the socket session for this client
        $socket->username = $username;
        // add the client's username to the global list
        array_push($names,$username);
         array_push($ids,$socket->id);
         var_dump($username.'  is online');
      $io->sockets->emit('client',$names,$ids);
           var_dump($names);
           var_dump($ids);
        $socket->addedUser = true;
       /* $socket->emit('login', array(
            'numUsers' => $numUsers
        ));*/
        }
    });

    // when the client emits 'typing', we broadcast it to others
    $socket->on('typing', function () use($socket) {
        $socket->broadcast->emit('typing', array(
            'username' => $socket->username
        ));
    });

    // when the client emits 'stop typing', we broadcast it to others
    $socket->on('stop typing', function () use($socket) {
        $socket->broadcast->emit('stop typing', array(
            'username' => $socket->username
        ));
    });

    // when the user disconnects.. perform this
    $socket->on('disconnect', function () use($socket) {
       global $names, $ids,$id,$io;
        // remove the username from global usernames list
        if(!$socket->username) return;// {
       $id=array_search($socket->id, $ids);
       unset($names[$id]);
       unset($ids[$id]);
         var_dump($id);
           // echo globally that this client has left
       $io->sockets->emit('client',$names,$ids);
        //}
   });

});

if (!defined('GLOBAL_START')) {
    Worker::runAll();
}
`

**Comment by walkor** [comment]
You can use ```$socket->join($user_id)``` In PHPSocket.IO and then use ```$emitter->in($user_id)->emit(...)``` to send message.

PHPSocket.IO side.
```php
<?php
use Workerman\Worker;
use Workerman\WebServer;
use Workerman\Autoloader;
use PHPSocketIO\SocketIO;

// Composer autoload
include '/your/path/vendor/autoload.php';

// =======Channel server========
$channel = new Channel\Server();

$io = new SocketIO(2020);
// ========ChannelAdapter========
$io->on('workerStart', function()use($io){
    $io->adapter('\PHPSocketIO\ChannelAdapter');
});
$io->on('connection', function($socket){
    // Login message
    $socket->on('login', function ($data)use($socket){
        $socket->join($data['user_id']);
    });
..............
```


```php
<?php
// composer autoload
include __DIR__ . '/your/path/vendor/autoload.php';
$emitter = new Emitter();
// Send message to $user_id
$emitter->in($user_id)->emit('new message', array('username'=>'test', 'message'=>'~~~~~~ok~~~~~~'));
```

**Comment by gunjotSinghMansa** [comment]
Very thanks for your help!! This works perfect!

Also, If there is any way to send message from PHP script to PHPSocketIO server?

**Comment by walkor** [comment]
Also see #5

**Comment by gunjotSinghMansa** [comment]
This helps a lot!! Very thanks for your help @walkor !

**Comment by walkor** [comment]
You are welcome.

**Comment by dorw123** [comment]
When I try this example I get Call to undefined method PHPSocketIO\Event\Emitter::in()

**Comment by walkor** [comment]
Not [PHPSocketIO\Event\Emitter](https://github.com/walkor/phpsocket.io/blob/master/src/Event/Emitter.php) but [Emitter](https://github.com/walkor/phpsocket.io-emitter/blob/master/src/Emitter.php).

**Comment by dorw123** [comment]
Thanks walkor. By the way, is there any way to join the user after login from server side without being triggered from client side?

**Comment by walkor** [comment]
No way.
