### ISSUE TITLE
how to send images in a chat or stream audio

### ISSUE THREAD

**Issue by devyaz** [walkor/phpsocket.io#84]
Hi @walkor , i was wondering how can one send images or voice call using phpsocketIO? or should i say the data chanel
like socketio-p2p?  am really interested in the images and voice .

**Comment by walkor** [comment]
Socketio-p2p seems  WebRTC example which I am not familiar with.

**Comment by devyaz** [comment]
ok maybe we can send using ajax!

**Comment by devyaz** [comment]
i did it using jquery file upload to upload to apache (php) then the callback has the link to the uploaded file which socketIO client sends to a private user using a "File" event, and it gets displayed on the receiving users page and the link is also save to mysql DB . but using Node server its even easier using socket.io-file.js!
