### ISSUE TITLE
WebSocket Transport support with socket.io-client-java

### ISSUE THREAD

**Issue by gunjotSinghMansa** [walkor/phpsocket.io#87]
socket.io-client-java  is not able to connect with phpsocket.io while forcing websocket transport. It works perfectly fine with Polling transport but phpsocket.io throws an **exception**, if i force websocket transport in socket.io-client-java.

----------

Below are warnings and exception returned by phpsocket.io

PHP Warning:  Missing argument 4 for PHPSocketIO\Engine\Engine::dealWebSocketConnect() in /var/www/html/socket/vendor/workerman/phpsocket.io/src/Engine/Engine.php on line 264

Warning: Missing argument 4 for PHPSocketIO\Engine\Engine::dealWebSocketConnect() in /var/www/html/socket/vendor/workerman/phpsocket.io/src/Engine/Engine.php on line 264
PHP Notice:  Undefined property: PHPSocketIO\Engine\Protocols\Http\Request::$res in /var/www/html/socket/vendor/workerman/phpsocket.io/src/Engine/Transports/Polling.php on line 14

Notice: Undefined property: PHPSocketIO\Engine\Protocols\Http\Request::$res in /var/www/html/socket/vendor/workerman/phpsocket.io/src/Engine/Transports/Polling.php on line 14
exception 'Exception' with message 'empty this->res' in /var/www/html/socket/vendor/workerman/phpsocket.io/src/Engine/Transports/PollingXHR.php:45
Stack trace:
#0 /var/www/html/socket/vendor/workerman/phpsocket.io/src/Engine/Transports/Polling.php(181): PHPSocketIO\Engine\Transports\PollingXHR->doWrite('?????0{"sid":"5...')
#1 /var/www/html/socket/vendor/workerman/phpsocket.io/src/Engine/Transports/Polling.php(176): PHPSocketIO\Engine\Transports\Polling->write('?????0{"sid":"5...')
#2 /var/www/html/socket/vendor/workerman/phpsocket.io/src/Engine/Socket.php(318): PHPSocketIO\Engine\Transports\Polling->send(Array)
#3 [internal function]: PHPSocketIO\Engine\Socket->flush()
#4 /var/www/html/socket/vendor/workerman/phpsocket.io/src/Event/Emitter.php(91): call_user_func_array(Array, Array)
#5 /var/www/html/socket/vendor/workerman/phpsocket.io/src/Engine/Transports/Polling.php(50): PHPSocketIO\Event\Emitter->emit('drain')
#6 /var/www/html/socket/vendor/workerman/phpsocket.io/src/Engine/Transports/Polling.php(18): PHPSocketIO\Engine\Transports\Polling->onPollRequest(Object(PHPSocketIO\Engine\Protocols\Http\Request), NULL)
#7 /var/www/html/socket/vendor/workerman/phpsocket.io/src/Engine/Transports/PollingXHR.php(28): PHPSocketIO\Engine\Transports\Polling->onRequest(Object(PHPSocketIO\Engine\Protocols\Http\Request))
#8 /var/www/html/socket/vendor/workerman/phpsocket.io/src/Engine/Engine.php(212): PHPSocketIO\Engine\Transports\PollingXHR->onRequest(Object(PHPSocketIO\Engine\Protocols\Http\Request))
#9 /var/www/html/socket/vendor/workerman/phpsocket.io/src/Engine/Engine.php(296): PHPSocketIO\Engine\Engine->handshake('websocket', Object(PHPSocketIO\Engine\Protocols\Http\Request))
#10 [internal function]: PHPSocketIO\Engine\Engine->dealWebSocketConnect(NULL, true, Object(PHPSocketIO\Engine\Protocols\Http\Request))
#11 /var/www/html/socket/vendor/workerman/phpsocket.io/src/Engine/Engine.php(142): call_user_func(Array, NULL, true, Object(PHPSocketIO\Engine\Protocols\Http\Request))
#12 /var/www/html/socket/vendor/workerman/phpsocket.io/src/Engine/Engine.php(133): PHPSocketIO\Engine\Engine->checkRequest(Object(PHPSocketIO\Engine\Protocols\Http\Request), Array)
#13 /var/www/html/socket/vendor/workerman/phpsocket.io/src/Engine/Engine.php(261): PHPSocketIO\Engine\Engine->verify(Object(PHPSocketIO\Engine\Protocols\Http\Request), Object(PHPSocketIO\Engine\Protocols\Http\Response), true, Array)
#14 [internal function]: PHPSocketIO\Engine\Engine->onWebSocketConnect(Object(Workerman\Connection\TcpConnection), Object(PHPSocketIO\Engine\Protocols\Http\Request), Object(PHPSocketIO\Engine\Protocols\Http\Response))
#15 /var/www/html/socket/vendor/workerman/phpsocket.io/src/Engine/Protocols/WebSocket/RFC6455.php(283): call_user_func_array(Array, Array)
#16 /var/www/html/socket/vendor/workerman/phpsocket.io/src/Engine/Protocols/WebSocket.php(84): PHPSocketIO\Engine\Protocols\WebSocket\RFC6455::dealHandshake(Object(Workerman\Connection\TcpConnection), Object(PHPSocketIO\Engine\Protocols\Http\Request), Object(PHPSocketIO\Engine\Protocols\Http\Response))
#17 /var/www/html/socket/vendor/workerman/phpsocket.io/src/Engine/Protocols/SocketIO.php(38): PHPSocketIO\Engine\Protocols\WebSocket::dealHandshake(Object(Workerman\Connection\TcpConnection), Object(PHPSocketIO\Engine\Protocols\Http\Request), Object(PHPSocketIO\Engine\Protocols\Http\Response))
#18 /var/www/html/socket/vendor/workerman/workerman/Connection/TcpConnection.php(444): PHPSocketIO\Engine\Protocols\SocketIO::input('GET /socket.io/...', Object(Workerman\Connection\TcpConnection))
#19 [internal function]: Workerman\Connection\TcpConnection->baseRead(Resource id #72)
#20 /var/www/html/socket/vendor/workerman/workerman/Events/Select.php(250): call_user_func_array(Array, Array)
#21 /var/www/html/socket/vendor/workerman/workerman/Worker.php(1537): Workerman\Events\Select->loop()
#22 /var/www/html/socket/vendor/workerman/workerman/Worker.php(936): Workerman\Worker->run()
#23 /var/www/html/socket/vendor/workerman/workerman/Worker.php(899): Workerman\Worker::forkOneWorker(Object(Workerman\Worker))
#24 /var/www/html/socket/vendor/workerman/workerman/Worker.php(431): Workerman\Worker::forkWorkers()
#25 /var/www/html/socket/connectionManager/Server.php(250): Workerman\Worker::runAll()

**Comment by walkor** [comment]
PHPSocket.IO maybe has some bug while forcing websocket transport.
But I have not much time to deal with it.
#79 seems to have fixed the problem, but I'm not sure.
Please try to check.

**Comment by freyo** [comment]
it works.
