### ISSUE TITLE
The examle doesnt works for me

### ISSUE THREAD

**Issue by csimpi** [walkor/phpsocket.io#9]
Sorry, but the example doesnt works for me.
The default path to the autoloader file is wrong.
If i change it i get this error:
Call to undefined function
Workerman\Lib\pcntl_signal() in .........\Lib\Timer.php on line 56

**Comment by walkor** [comment]
Phpsocket.io require pcntl extension.

**Comment by csimpi** [comment]
Ah i see... :( i cant use with wamp server because pcntl exists only on linux :(

**Comment by walkor** [comment]
Try this https://github.com/walkor/phpsocket.io-for-win.

**Comment by csimpi** [comment]
Thank you i will! :)

**Comment by csimpi** [comment]
One more question. Can i use this php-server version with linux? Because i develope in WAMP but i will use on public Linux server.

**Comment by walkor** [comment]
Yes you can.

**Comment by csimpi** [comment]
Thanks it works like a charm!

**Comment by walkor** [comment]
You are welcome.

**Comment by walkor** [comment]
@shamimmoeen your project is not right.

```F:\WinProgramme\xampp\htdocs\phpsocket.io-mas
ter``` is not like the directory structure of the phpsocket.io-for-win project but phpsocket.io.
