### ISSUE TITLE
Need a examples to use multi-rooms (chat etc)

### ISSUE THREAD

**Issue by tihoho** [walkor/phpsocket.io#90]
Hey Walkor. Please add tiny examples to use phpsocket.io as multi-rooms. (this is making via groups to/leave/join? or how?

**Comment by walkor** [comment]
Sorry for the delay response. Unfortunately I have not much time to do this recently.

Here is [an example](https://github.com/walkor/web-msg-sender/blob/master/start_io.php) for ```join/to``` hope that can help you .

And this is [an example](https://github.com/walkor/phpsocket.io/blob/master/examples/chat/start_io.php) for chat room but with out using ```to/join/leave```

Or some body can provide an examples？

**Comment by tihoho** [comment]
Thanks for the feedback and links. 
I've already figured out that for the rooms i need to use the join/leave/to mechanisms.

**Comment by tihoho** [comment]
Thanks for the feedback and links. 
I've already figured out that for the rooms i need to use the join/leave/to mechanisms.
