### ISSUE TITLE
Count users a especific room

### ISSUE THREAD

**Issue by DavidWilliamBalbino** [walkor/phpsocket.io#91]
Hello Walkor,
How do I tell users from a specific room?

**Comment by walkor** [comment]
Sorry.
I don't understand your problem.
Can you describe it in more detail?

**Comment by DavidWilliamBalbino** [comment]
For example,

I have two users connected in room

$socket->join('test');

How get total number of users in room test?

**Comment by walkor** [comment]
You should use a global variable to  store the count.
For example.
```php
global $room_count_array;
$socket->join('room1');
$room_count_array['room1']++;
```

Some examples .
https://github.com/walkor/phpsocket.io/blob/master/examples/chat/start_io.php
https://github.com/walkor/web-msg-sender/blob/master/start_io.php

**Comment by DavidWilliamBalbino** [comment]
Thanks, I just thought there was a native way of doing this.

Many thanks for the attention, and congratulations for the code, it's perfect
