### ISSUE TITLE
Chat example not working on Hosted Server

### ISSUE THREAD

**Issue by klee0589** [walkor/phpsocket.io#94]
I am currently trying to run the chat example as a starting point on my server.
I keep on getting the following error. This same issue occurred when I was testing in my local development environment but fixed it once I updated PHP to 7. PHP is updated on the server as well but this seems to be an issue with not listening to the correct port. Please advise on what I should do.

![screen shot 2017-06-12 at 12 08 33 pm](https://user-images.githubusercontent.com/10567488/27043359-e60cee92-4f67-11e7-9729-c2b2b7b3c321.png)

**Comment by walkor** [comment]
Please run phpsocket.io as debug mode with command "php start.php start".
And then see is there any errors on terminal?

**Comment by klee0589** [comment]
Im sorry. I forgot to mention it is on my hosted server. But, I was able to run it with debug mode and it is working fine. But, because my server is using HTTPS secure protocol I was only able to get it to work when I change the url to HTTP. How can I use the secure protocol with this library? I see a lot of workaround for the original Socket.io with Node.js.
