### ISSUE TITLE
is there any plan to add binary support?

### ISSUE THREAD

**Issue by ayaka209** [walkor/phpsocket.io#97]
now we can't send any binary data.

**Comment by walkor** [comment]
Sorry, there are no specific plans.

**Comment by tihoho** [comment]
@ayaka209 you want a stream-binary data, or just binary like as images, files? If you want second variant, you can use base64 as coder for files and package structure like as:
```
...->emit('file', [
   'file' => 'The_file.pdf',
   'type' => 'image',
   'data' => base64_encode(file_get_contents($filePath)),
]);
```

**Comment by LuckyCyborg** [comment]
Honestly, I do not know how big chunks of data can be sent via an event on PHPSocketIO...

@walkor you have some estimations about this subject?
