### ISSUE TITLE
Use different channel port

### ISSUE THREAD

**Issue by tolew1** [walkor/phpsocket.io#99]
I've tried to change the channel port from using info from this issue #55 but I keep getting an error.

`$io->on('workerStart', function()use($io){
	ChannelAdapter::$port = 3206;
    $io->adapter('\PHPSocketIO\ChannelAdapter');
});`

I get this error 

**Error: Class 'ChannelAdapter' not found in /opt/sockets/server.php:40**

I have this declared. 

```
use Workerman\Worker;
use Workerman\WebServer;
use Workerman\Autoloader;
use PHPSocketIO\SocketIO;
```

What am I doing wrong here?

**Comment by walkor** [comment]
Please add this declared.
```
use PHPSocketIO\ChannelAdapter;
```

**Comment by tolew1** [comment]
Thanks that fixed that issue but I keep also getting this

```
 PHP Warning:  stream_socket_client(): unable to connect to tcp://127.0.0.1:3206 (Connection refused) in /opt/vendor/workerman/phpsocket.io-emitter/src/Emitter.php on line 25
[16-Jul-2017 04:44:01 UTC] PHP Fatal error:  Uncaught Exception: Connection refused in /opt/vendor/workerman/phpsocket.io-emitter/src/Emitter.php:28
Stack trace:
```
It shouldn't be a firewall issue since it's local host. But the port is open anyway.

**Comment by walkor** [comment]
You should start a channel server with codes like this.
```php
$channel = new Channel\Server('0.0.0.0', 3206);
```

**Comment by tolew1** [comment]
Great thanks for the quick responses.
